<?php

use Illuminate\Support\Facades\Route;
use Modules\Construction\Http\Controllers\DashboardController;
use Modules\Construction\Http\Controllers\InstallController;
use Modules\Construction\Http\Controllers\ProjectController;
use Modules\Construction\Http\Controllers\BoqController;
use Modules\Construction\Http\Controllers\CostCodeController;
use Modules\Construction\Http\Controllers\MeasurementController;
use Modules\Construction\Http\Controllers\CustomerCertificateController;
use Modules\Construction\Http\Controllers\BoqSpreadsheetController;
use Modules\Construction\Http\Controllers\ContractController;
use Modules\Construction\Http\Controllers\PrintFontController;
use Modules\Construction\Http\Controllers\QuoteController;
use Modules\Construction\Http\Controllers\ContractAdjustmentController;
use Modules\Construction\Http\Controllers\MaterialController;
use Modules\Construction\Http\Controllers\LaborController;
use Modules\Construction\Http\Controllers\SubcontractorController;
use Modules\Construction\Http\Controllers\SubcontractCertificateController;
use Modules\Construction\Http\Controllers\SubcontractPaymentController;
use Modules\Construction\Http\Controllers\SubcontractRetentionReleaseController;
use Modules\Construction\Http\Controllers\FinancialReportController;
use Modules\Construction\Http\Controllers\SubcontractorStatementController;
use Modules\Construction\Http\Controllers\BoqSubcontractComparisonController;
use Modules\Construction\Http\Controllers\BoqCostProfitabilityController;
use Modules\Construction\Http\Controllers\CustomerCertificatesCollectionController;
use Modules\Construction\Http\Controllers\CustomerRetentionReleaseController;
use Modules\Construction\Http\Controllers\RetentionGuaranteesReportController;
use Modules\Construction\Http\Controllers\AccountingSettingsController;
use Modules\Construction\Http\Controllers\SettingsController;

Route::middleware([
    'web',
    'SetSessionData',
    'auth',
    'language',
    'timezone',
    'AdminSidebarMenu',
])->prefix('construction')->name('construction.')->group(function () {
    Route::get('/install', [InstallController::class, 'index'])->name('install.index');
    Route::post('/install', [InstallController::class, 'install'])->name('install.store');
    Route::get('/install/uninstall', [InstallController::class, 'uninstall'])->name('install.uninstall');
    Route::get('/install/update', [InstallController::class, 'update'])->name('install.update');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('overview', [DashboardController::class, 'overview'])->name('overview.index');
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::get('settings/accounting', [AccountingSettingsController::class, 'index'])->name('settings.accounting.index');
    Route::post('settings/accounting/create-accounts', [AccountingSettingsController::class, 'createAccounts'])->name('settings.accounting.create-accounts');
    Route::put('settings/accounting', [AccountingSettingsController::class, 'update'])->name('settings.accounting.update');
    Route::get('project-items', [BoqController::class, 'workspaceIndex'])->name('project-items.index');
    Route::get('contracts', [ContractController::class, 'index'])->name('contracts.index');
    Route::get('measurements', [MeasurementController::class, 'workspaceIndex'])->name('measurements.index');
    Route::get('ipcs', [CustomerCertificateController::class, 'workspaceIndex'])->name('ipcs.index');
    Route::get('costs', [DashboardController::class, 'costs'])->name('costs.index');
    Route::get('costs/materials', [MaterialController::class, 'index'])->name('materials.index');
    Route::get('costs/materials/create', [MaterialController::class, 'create'])->name('materials.create');
    Route::post('costs/materials', [MaterialController::class, 'store'])->name('materials.store');
    Route::get('costs/materials/{document}/edit', [MaterialController::class, 'edit'])->name('materials.edit');
    Route::put('costs/materials/{document}', [MaterialController::class, 'update'])->name('materials.update');
    Route::delete('costs/materials/{document}', [MaterialController::class, 'destroy'])->name('materials.destroy');
    Route::get('costs/materials/{document}/preview', [MaterialController::class, 'preview'])->name('materials.preview');
    Route::get('costs/materials/{document}/print', [MaterialController::class, 'print'])->name('materials.print');
    Route::get('costs/materials/{document}', [MaterialController::class, 'show'])->name('materials.show');
    Route::post('costs/materials/{document}/lines', [MaterialController::class, 'storeLine'])->name('materials.lines.store');
    Route::put('costs/materials/{document}/lines/{line}', [MaterialController::class, 'updateLine'])->name('materials.lines.update');
    Route::delete('costs/materials/{document}/lines/{line}', [MaterialController::class, 'destroyLine'])->name('materials.lines.destroy');
    Route::post('costs/materials/{document}/approve', [MaterialController::class, 'approve'])->name('materials.approve');
    Route::get('costs/materials/{document}/returns/create', [MaterialController::class, 'createReturn'])->name('materials.returns.create');
    Route::post('costs/materials/{document}/returns', [MaterialController::class, 'storeReturn'])->name('materials.returns.store');
    Route::get('costs/labor', [LaborController::class, 'index'])->name('labor.index');
    Route::get('costs/labor/create', [LaborController::class, 'create'])->name('labor.create');
    Route::post('costs/labor', [LaborController::class, 'store'])->name('labor.store');
    Route::get('costs/labor/{sheet}/edit', [LaborController::class, 'edit'])->name('labor.edit');
    Route::put('costs/labor/{sheet}', [LaborController::class, 'update'])->name('labor.update');
    Route::delete('costs/labor/{sheet}', [LaborController::class, 'destroy'])->name('labor.destroy');
    Route::get('costs/labor/{sheet}/preview', [LaborController::class, 'preview'])->name('labor.preview');
    Route::get('costs/labor/{sheet}/print', [LaborController::class, 'print'])->name('labor.print');
    Route::get('costs/labor/{sheet}', [LaborController::class, 'show'])->name('labor.show');
    Route::post('costs/labor/{sheet}/lines', [LaborController::class, 'storeLine'])->name('labor.lines.store');
    Route::put('costs/labor/{sheet}/lines/{line}', [LaborController::class, 'updateLine'])->name('labor.lines.update');
    Route::delete('costs/labor/{sheet}/lines/{line}', [LaborController::class, 'destroyLine'])->name('labor.lines.destroy');
    Route::post('costs/labor/{sheet}/approve', [LaborController::class, 'approve'])->name('labor.approve');
    Route::post('costs/labor/{sheet}/cancel', [LaborController::class, 'cancel'])->name('labor.cancel');
    Route::get('subcontractors', [SubcontractorController::class, 'index'])->name('subcontractors.index');
    Route::post('subcontractors', [SubcontractorController::class, 'store'])->name('subcontractors.store');
    Route::get('subcontractors/{subcontract}/preview', [SubcontractorController::class, 'preview'])->name('subcontractors.preview');
    Route::get('subcontractors/{subcontract}/print', [SubcontractorController::class, 'print'])->name('subcontractors.print');
    Route::get('subcontractors/{subcontract}', [SubcontractorController::class, 'show'])->name('subcontractors.show');
    Route::put('subcontractors/{subcontract}', [SubcontractorController::class, 'update'])->name('subcontractors.update');
    Route::delete('subcontractors/{subcontract}', [SubcontractorController::class, 'destroy'])->name('subcontractors.destroy');
    Route::post('subcontractors/{subcontract}/items', [SubcontractorController::class, 'storeItem'])->name('subcontractors.items.store');
    Route::put('subcontractors/{subcontract}/items/{item}', [SubcontractorController::class, 'updateItem'])->name('subcontractors.items.update');
    Route::delete('subcontractors/{subcontract}/items/{item}', [SubcontractorController::class, 'destroyItem'])->name('subcontractors.items.destroy');
    Route::post('subcontractors/{subcontract}/approve', [SubcontractorController::class, 'approve'])->name('subcontractors.approve');
    Route::post('subcontractors/{subcontract}/certificates', [SubcontractCertificateController::class, 'store'])->name('subcontractors.certificates.store');
    Route::get('subcontractors/{subcontract}/certificates/{certificate}/preview', [SubcontractCertificateController::class, 'preview'])->name('subcontractors.certificates.preview');
    Route::get('subcontractors/{subcontract}/certificates/{certificate}/print', [SubcontractCertificateController::class, 'print'])->name('subcontractors.certificates.print');
    Route::get('subcontractors/{subcontract}/certificates/{certificate}', [SubcontractCertificateController::class, 'show'])->name('subcontractors.certificates.show');
    Route::put('subcontractors/{subcontract}/certificates/{certificate}', [SubcontractCertificateController::class, 'update'])->name('subcontractors.certificates.update');
    Route::delete('subcontractors/{subcontract}/certificates/{certificate}', [SubcontractCertificateController::class, 'destroy'])->name('subcontractors.certificates.destroy');
    Route::post('subcontractors/{subcontract}/certificates/{certificate}/approve', [SubcontractCertificateController::class, 'approve'])->name('subcontractors.certificates.approve');
    Route::patch('subcontractors/{subcontract}/certificates/{certificate}/retention-due-date', [SubcontractCertificateController::class, 'updateRetentionDueDate'])->name('subcontractors.certificates.retention-due-date.update');
    Route::post('subcontractors/{subcontract}/certificates/{certificate}/payments', [SubcontractPaymentController::class, 'store'])->name('subcontractors.certificates.payments.store');
    Route::get('subcontractors/{subcontract}/certificates/{certificate}/payments/{payment}/preview', [SubcontractPaymentController::class, 'preview'])->name('subcontractors.certificates.payments.preview');
    Route::get('subcontractors/{subcontract}/certificates/{certificate}/payments/{payment}/print', [SubcontractPaymentController::class, 'print'])->name('subcontractors.certificates.payments.print');
    Route::post('subcontractors/{subcontract}/certificates/{certificate}/retention-releases', [SubcontractRetentionReleaseController::class, 'store'])->name('subcontractors.certificates.retention-releases.store');
    Route::post('subcontractors/{subcontract}/certificates/{certificate}/retention-releases/{release}/cancel', [SubcontractRetentionReleaseController::class, 'cancel'])->name('subcontractors.certificates.retention-releases.cancel');
    Route::get('reports', [FinancialReportController::class, 'index'])->name('reports.index');
    Route::get('reports/financial-position/print', [FinancialReportController::class, 'print'])->name('reports.financial-position.print');
    Route::get('reports/subcontractor-statement', [SubcontractorStatementController::class, 'index'])->name('reports.subcontractor-statement.index');
    Route::get('reports/subcontractor-statement/print', [SubcontractorStatementController::class, 'print'])->name('reports.subcontractor-statement.print');
    Route::get('reports/boq-subcontract-comparison', [BoqSubcontractComparisonController::class, 'index'])->name('reports.boq-subcontract-comparison.index');
    Route::get('reports/boq-subcontract-comparison/print', [BoqSubcontractComparisonController::class, 'print'])->name('reports.boq-subcontract-comparison.print');
    Route::get('reports/boq-cost-profitability', [BoqCostProfitabilityController::class, 'index'])->name('reports.boq-cost-profitability.index');
    Route::get('reports/boq-cost-profitability/print', [BoqCostProfitabilityController::class, 'print'])->name('reports.boq-cost-profitability.print');
    Route::get('reports/customer-certificates-collection', [CustomerCertificatesCollectionController::class, 'index'])->name('reports.customer-certificates-collection.index');
    Route::get('reports/customer-certificates-collection/print', [CustomerCertificatesCollectionController::class, 'print'])->name('reports.customer-certificates-collection.print');
    Route::get('reports/retention-guarantees', [RetentionGuaranteesReportController::class, 'index'])->name('reports.retention-guarantees.index');
    Route::get('reports/retention-guarantees/print', [RetentionGuaranteesReportController::class, 'print'])->name('reports.retention-guarantees.print');
    Route::get('print-font/{weight}', [PrintFontController::class, 'show'])->name('print-font');
    Route::get('quotes', [QuoteController::class, 'index'])->name('quotes.index');
    Route::post('quotes', [QuoteController::class, 'store'])->name('quotes.store');
    Route::get('quotes/{quote}', [QuoteController::class, 'show'])->name('quotes.show');
    Route::put('quotes/{quote}', [QuoteController::class, 'update'])->name('quotes.update');
    Route::delete('quotes/{quote}', [QuoteController::class, 'destroy'])->name('quotes.destroy');
    Route::post('quotes/{quote}/items', [QuoteController::class, 'storeItems'])->name('quotes.items.store');
    Route::put('quotes/{quote}/items/{item}', [QuoteController::class, 'updateItem'])->name('quotes.items.update');
    Route::delete('quotes/{quote}/items/{item}', [QuoteController::class, 'destroyItem'])->name('quotes.items.destroy');
    Route::post('quotes/{quote}/status', [QuoteController::class, 'status'])->name('quotes.status');
    Route::post('quotes/{quote}/convert', [QuoteController::class, 'convert'])->name('quotes.convert');
    Route::get('quotes/{quote}/preview', [QuoteController::class, 'preview'])->name('quotes.preview');
    Route::get('quotes/{quote}/print', [QuoteController::class, 'print'])->name('quotes.print');
    Route::get('quotes/{quote}/pdf', [QuoteController::class, 'pdf'])->name('quotes.pdf');
    Route::resource('projects', ProjectController::class);
    Route::get('projects/{project}/contracts/create', [ContractController::class, 'create'])->name('projects.contracts.create');
    Route::post('projects/{project}/contracts', [ContractController::class, 'store'])->name('projects.contracts.store');
    Route::get('projects/{project}/contracts/{contract}', [ContractController::class, 'show'])->name('projects.contracts.show');
    Route::get('projects/{project}/contracts/{contract}/edit', [ContractController::class, 'edit'])->name('projects.contracts.edit');
    Route::put('projects/{project}/contracts/{contract}', [ContractController::class, 'update'])->name('projects.contracts.update');
    Route::post('projects/{project}/contracts/{contract}/activate', [ContractController::class, 'activate'])->name('projects.contracts.activate');
    Route::get('projects/{project}/contracts/{contract}/preview', [ContractController::class, 'preview'])->name('projects.contracts.preview');
    Route::get('projects/{project}/contracts/{contract}/print', [ContractController::class, 'print'])->name('projects.contracts.print');
    Route::get('projects/{project}/contracts/{contract}/pdf', [ContractController::class, 'pdf'])->name('projects.contracts.pdf');
    Route::get('projects/{project}/contracts/{contract}/adjustments', [ContractAdjustmentController::class, 'index'])->name('projects.contracts.adjustments.index');
    Route::post('projects/{project}/contracts/{contract}/adjustments', [ContractAdjustmentController::class, 'store'])->name('projects.contracts.adjustments.store');
    Route::put('projects/{project}/contracts/{contract}/adjustments/{adjustment}', [ContractAdjustmentController::class, 'update'])->name('projects.contracts.adjustments.update');
    Route::delete('projects/{project}/contracts/{contract}/adjustments/{adjustment}', [ContractAdjustmentController::class, 'destroy'])->name('projects.contracts.adjustments.destroy');
    Route::post('projects/{project}/contracts/{contract}/adjustments/{adjustment}/approve', [ContractAdjustmentController::class, 'approve'])->name('projects.contracts.adjustments.approve');
    Route::get('projects/{project}/boq', [BoqController::class, 'index'])->name('projects.boq.index');
    Route::post('projects/{project}/boq', [BoqController::class, 'storeVersion'])->name('projects.boq.store');
    Route::get('projects/{project}/boq/{version}', [BoqController::class, 'show'])->name('projects.boq.show');
    Route::post('projects/{project}/boq/{version}/items', [BoqController::class, 'storeItem'])->name('projects.boq.items.store');
    Route::put('projects/{project}/boq/{version}/items/{item}', [BoqController::class, 'updateItem'])->name('projects.boq.items.update');
    Route::delete('projects/{project}/boq/{version}/items/{item}', [BoqController::class, 'destroyItem'])->name('projects.boq.items.destroy');
    Route::post('projects/{project}/boq/{version}/items/{item}/costs', [BoqController::class, 'storeAllocation'])->name('projects.boq.costs.store');
    Route::delete('projects/{project}/boq/{version}/items/{item}/costs/{allocation}', [BoqController::class, 'destroyAllocation'])->name('projects.boq.costs.destroy');
    Route::post('projects/{project}/boq/{version}/approve', [BoqController::class, 'approve'])->name('projects.boq.approve');
    Route::post('projects/{project}/boq/{version}/revise', [BoqController::class, 'revise'])->name('projects.boq.revise');
    Route::get('boq/import-template', [BoqSpreadsheetController::class, 'template'])->name('boq.import-template');
    Route::get('projects/{project}/boq/{version}/export', [BoqSpreadsheetController::class, 'export'])->name('projects.boq.export');
    Route::post('projects/{project}/boq/{version}/import-preview', [BoqSpreadsheetController::class, 'preview'])->name('projects.boq.import.preview');
    Route::get('projects/{project}/boq/{version}/import-review/{token}', [BoqSpreadsheetController::class, 'review'])->name('projects.boq.import.review');
    Route::post('projects/{project}/boq/{version}/import-commit/{token}', [BoqSpreadsheetController::class, 'commit'])->name('projects.boq.import.commit');
    Route::get('cost-codes', [CostCodeController::class, 'index'])->name('cost-codes.index');
    Route::post('cost-codes', [CostCodeController::class, 'store'])->name('cost-codes.store');
    Route::get('projects/{project}/measurements', [MeasurementController::class, 'index'])->name('projects.measurements.index');
    Route::post('projects/{project}/measurements', [MeasurementController::class, 'store'])->name('projects.measurements.store');
    Route::get('projects/{project}/measurements/{measurement}', [MeasurementController::class, 'show'])->name('projects.measurements.show');
    Route::post('projects/{project}/measurements/{measurement}/items', [MeasurementController::class, 'storeItem'])->name('projects.measurements.items.store');
    Route::delete('projects/{project}/measurements/{measurement}/items/{item}', [MeasurementController::class, 'destroyItem'])->name('projects.measurements.items.destroy');
    Route::post('projects/{project}/measurements/{measurement}/approve', [MeasurementController::class, 'approve'])->name('projects.measurements.approve');
    Route::get('projects/{project}/certificates', [CustomerCertificateController::class, 'index'])->name('projects.certificates.index');
    Route::post('projects/{project}/certificates', [CustomerCertificateController::class, 'store'])->name('projects.certificates.store');
    Route::get('projects/{project}/certificates/{certificate}', [CustomerCertificateController::class, 'show'])->name('projects.certificates.show');
    Route::post('projects/{project}/certificates/{certificate}/approve', [CustomerCertificateController::class, 'approve'])->name('projects.certificates.approve');
    Route::post('projects/{project}/certificates/{certificate}/cancel', [CustomerCertificateController::class, 'cancel'])->name('projects.certificates.cancel');
    Route::patch('projects/{project}/certificates/{certificate}/retention-due-date', [CustomerCertificateController::class, 'updateRetentionDueDate'])->name('projects.certificates.retention-due-date.update');
    Route::get('projects/{project}/certificates/{certificate}/preview', [CustomerCertificateController::class, 'preview'])->name('projects.certificates.preview');
    Route::get('projects/{project}/certificates/{certificate}/print', [CustomerCertificateController::class, 'print'])->name('projects.certificates.print');
    Route::get('projects/{project}/certificates/{certificate}/pdf', [CustomerCertificateController::class, 'pdf'])->name('projects.certificates.pdf');
    Route::post('projects/{project}/certificates/{certificate}/invoice', [CustomerCertificateController::class, 'createInvoice'])->name('projects.certificates.invoice');
    Route::post('projects/{project}/certificates/{certificate}/retention-releases', [CustomerRetentionReleaseController::class, 'store'])->name('projects.certificates.retention-releases.store');
    Route::post('projects/{project}/certificates/{certificate}/retention-releases/{release}/cancel', [CustomerRetentionReleaseController::class, 'cancel'])->name('projects.certificates.retention-releases.cancel');
});
