@extends('construction::layouts.module')

@section('title', __('construction::lang.retention_guarantees_report'))

@section('module_content')
<section class="content ct-financial-report-page ct-retention-report-page">
    <nav class="ct-report-switcher" aria-label="@lang('construction::lang.construction_reports')">
        <a href="{{ route('construction.reports.index') }}"><i class="fa fa-chart-line"></i> @lang('construction::lang.financial_position_report')</a>
        <a href="{{ route('construction.reports.subcontractor-statement.index') }}"><i class="fa fa-file-invoice-dollar"></i> @lang('construction::lang.subcontractor_statement')</a>
        <a href="{{ route('construction.reports.boq-subcontract-comparison.index') }}"><i class="fa fa-balance-scale"></i> @lang('construction::lang.boq_subcontract_comparison')</a>
        <a href="{{ route('construction.reports.boq-cost-profitability.index') }}"><i class="fa fa-coins"></i> @lang('construction::lang.boq_cost_profitability')</a>
        <a href="{{ route('construction.reports.customer-certificates-collection.index') }}"><i class="fa fa-hand-holding-usd"></i> @lang('construction::lang.customer_collection_report')</a>
        <a class="is-active" href="{{ route('construction.reports.retention-guarantees.index') }}"><i class="fa fa-shield-alt"></i> @lang('construction::lang.retention_guarantees_report')</a>
    </nav>

    <header class="ct-financial-report-heading"><div><span><i class="fa fa-calendar-check"></i> @lang('construction::lang.retention_control')</span><h1>@lang('construction::lang.retention_guarantees_report')</h1><p>@lang('construction::lang.retention_guarantees_description')</p></div><a class="btn ct-primary-action" target="_blank" href="{{ route('construction.reports.retention-guarantees.print',array_filter(['project_id'=>$projectId,'to_date'=>$toDate,'party_type'=>$partyType,'due_status'=>$dueStatus])) }}"><i class="fa fa-print"></i> @lang('construction::lang.print_retention_report')</a></header>

    <form method="GET" action="{{ route('construction.reports.retention-guarantees.index') }}" class="ct-financial-report-filter ct-retention-filter">
        <div class="form-group"><label>@lang('construction::lang.project')</label><select name="project_id" class="form-control select2"><option value="">@lang('construction::lang.statement_all_projects')</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected($projectId === $project->id)>{{ $project->code }} — {{ $project->name }}</option>@endforeach</select></div>
        <div class="form-group"><label>@lang('construction::lang.party_type')</label><select name="party_type" class="form-control"><option value="">@lang('construction::lang.all_parties')</option><option value="customer" @selected($partyType==='customer')>@lang('construction::lang.customer_retentions')</option><option value="subcontractor" @selected($partyType==='subcontractor')>@lang('construction::lang.subcontractor_retentions')</option></select></div>
        <div class="form-group"><label>@lang('construction::lang.due_status')</label><select name="due_status" class="form-control"><option value="">@lang('construction::lang.all_statuses')</option>@foreach(['due','upcoming','not_due','no_date','closed'] as $status)<option value="{{ $status }}" @selected($dueStatus===$status)>@lang('construction::lang.due_status_'.$status)</option>@endforeach</select></div>
        <div class="form-group"><label>@lang('construction::lang.as_of_date')</label><input name="to_date" value="{{ @format_date($toDate) }}" class="form-control ct-date-picker" readonly></div>
        <button class="btn btn-primary"><i class="fa fa-filter"></i> @lang('construction::lang.show_report')</button>
    </form>

    <div class="ct-retention-context"><span><small>@lang('construction::lang.project')</small><strong>{{ $selectedProject ? $selectedProject->code.' — '.$selectedProject->name : __('construction::lang.statement_all_projects') }}</strong></span><span><small>@lang('construction::lang.as_of_date')</small><strong>{{ @format_date($toDate) }}</strong></span><span><small>@lang('construction::lang.retentions_without_dates')</small><strong>{{ $report['summary']['no_date_count'] }}</strong></span></div>

    <div class="ct-retention-kpis">
        <article class="is-right"><small>@lang('construction::lang.customer_retentions')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['customer_retention']])</strong><span>@lang('construction::lang.rights_held_by_customers')</span></article>
        <article><small>@lang('construction::lang.subcontract_original_retention')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['subcontract_original']])</strong><span>@lang('construction::lang.original_retention')</span></article>
        <article class="is-released"><small>@lang('construction::lang.released_retention')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['subcontract_released']])</strong><span>@lang('construction::lang.paid_to_subcontractors')</span></article>
        <article class="is-liability"><small>@lang('construction::lang.remaining_retention')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['subcontract_remaining']])</strong><span>@lang('construction::lang.liabilities_to_subcontractors')</span></article>
        <article class="{{ $report['summary']['net_position'] >= 0 ? 'is-right' : 'is-liability' }}"><small>@lang('construction::lang.net_retention_position')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['net_position']])</strong><span>@lang('construction::lang.rights_less_liabilities')</span></article>
    </div>

    <section class="ct-retention-outlook"><header><span>@lang('construction::lang.retention_cash_outlook')</span><small>@lang('construction::lang.next_thirty_days')</small></header><div><article><small>@lang('construction::lang.customer_due_now')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['due_customer']])</strong></article><article><small>@lang('construction::lang.subcontract_due_now')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['due_subcontractor']])</strong></article><article><small>@lang('construction::lang.customer_due_30')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['upcoming_customer']])</strong></article><article><small>@lang('construction::lang.subcontract_due_30')</small><strong>@include('construction::partials.money',['value'=>$report['summary']['upcoming_subcontractor']])</strong></article></div></section>

    <div class="ct-retention-note"><i class="fa fa-info-circle"></i> @lang('construction::lang.customer_retention_no_release_notice')</div>

    <section class="ct-financial-table-panel ct-retention-table-panel"><header><div><span>@lang('construction::lang.rights_held_by_customers')</span><h2>@lang('construction::lang.customer_retentions')</h2></div><strong>@include('construction::partials.money',['value'=>$report['summary']['customer_retention']])</strong></header><div class="table-responsive"><table class="table ct-financial-table"><thead><tr><th>@lang('construction::lang.project')</th><th>@lang('construction::lang.customer')</th><th>@lang('construction::lang.certificate')</th><th>@lang('construction::lang.original_retention')</th><th>@lang('construction::lang.expected_release_date')</th><th>@lang('construction::lang.due_status')</th></tr></thead><tbody>@forelse($report['customer_rows'] as $row)<tr><td><strong>{{ $row['project']?->code }} — {{ $row['project']?->name }}</strong></td><td>{{ $row['party_name'] }}</td><td><strong dir="ltr">{{ $row['certificate']->number }}</strong><small>{{ @format_date($row['certificate']->certificate_date) }}</small></td><td><strong>@include('construction::partials.money',['value'=>$row['remaining']])</strong></td><td>{{ $row['retention_due_date'] ? @format_date($row['retention_due_date']) : __('construction::lang.no_due_date') }}</td><td><span class="ct-due-status is-{{ $row['due_status'] }}">@lang('construction::lang.due_status_'.$row['due_status'])</span>@if($row['days_until_due'] !== null)<small>{{ abs($row['days_until_due']) }} @lang($row['days_until_due'] <= 0 ? 'construction::lang.overdue_days' : 'construction::lang.days_remaining')</small>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">@lang('construction::lang.no_customer_retentions')</td></tr>@endforelse</tbody></table></div></section>

    <section class="ct-financial-table-panel ct-retention-table-panel"><header><div><span>@lang('construction::lang.liabilities_to_subcontractors')</span><h2>@lang('construction::lang.subcontractor_retentions')</h2></div><strong>@include('construction::partials.money',['value'=>$report['summary']['subcontract_remaining']])</strong></header><div class="table-responsive"><table class="table ct-financial-table"><thead><tr><th>@lang('construction::lang.project')</th><th>@lang('construction::lang.subcontractor')</th><th>@lang('construction::lang.certificate')</th><th>@lang('construction::lang.original_retention')</th><th>@lang('construction::lang.released_retention')</th><th>@lang('construction::lang.remaining_retention')</th><th>@lang('construction::lang.expected_release_date')</th><th>@lang('construction::lang.release_status')</th><th>@lang('construction::lang.due_status')</th></tr></thead><tbody>@forelse($report['subcontractor_rows'] as $row)<tr><td><strong>{{ $row['project']?->code }} — {{ $row['project']?->name }}</strong></td><td><strong>{{ $row['party_name'] }}</strong><small dir="ltr">{{ $row['agreement_number'] }}</small></td><td><strong dir="ltr">{{ $row['certificate']->number }}</strong><small>{{ @format_date($row['certificate']->certificate_date) }}</small></td><td>@include('construction::partials.money',['value'=>$row['original']])</td><td>@include('construction::partials.money',['value'=>$row['released']])</td><td><strong>@include('construction::partials.money',['value'=>$row['remaining']])</strong></td><td>{{ $row['retention_due_date'] ? @format_date($row['retention_due_date']) : __('construction::lang.no_due_date') }}</td><td><span class="ct-release-status is-{{ $row['release_status'] }}">@lang('construction::lang.release_status_'.$row['release_status'])</span></td><td><span class="ct-due-status is-{{ $row['due_status'] }}">@lang('construction::lang.due_status_'.$row['due_status'])</span>@if($row['days_until_due'] !== null)<small>{{ abs($row['days_until_due']) }} @lang($row['days_until_due'] <= 0 ? 'construction::lang.overdue_days' : 'construction::lang.days_remaining')</small>@endif</td></tr>@empty<tr><td colspan="9" class="text-center text-muted">@lang('construction::lang.no_subcontract_retentions')</td></tr>@endforelse</tbody></table></div></section>
</section>
@endsection

@push('ct_quick_css')
<style>.ct-financial-report-filter.ct-retention-filter{grid-template-columns:1.5fr 1fr 1fr .8fr auto}.ct-report-switcher{max-width:100%;overflow-x:auto}.ct-retention-context{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px;margin:14px 0}.ct-retention-context span,.ct-retention-note{padding:12px 15px;border:1px solid #dce6f0;border-radius:10px;background:#fff}.ct-retention-context small,.ct-retention-context strong{display:block}.ct-retention-context small{color:#77879a}.ct-retention-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.ct-retention-kpis article{padding:15px;border:1px solid #dce6f0;border-top:4px solid #50739a;border-radius:12px;background:#fff}.ct-retention-kpis article.is-right{border-top-color:#13986f}.ct-retention-kpis article.is-liability{border-top-color:#cf4555}.ct-retention-kpis article.is-released{border-top-color:#2382c9}.ct-retention-kpis small,.ct-retention-kpis strong,.ct-retention-kpis span{display:block}.ct-retention-kpis strong{margin:8px 0;font-size:20px;color:#173d70}.ct-retention-kpis span{font-size:14px;color:#77879a}.ct-retention-outlook{margin:15px 0;padding:15px;border-radius:12px;background:#173d70;color:#fff}.ct-retention-outlook header{display:flex;justify-content:space-between}.ct-retention-outlook>div{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.ct-retention-outlook article{padding:11px;border-radius:9px;background:rgba(255,255,255,.1)}.ct-retention-outlook small,.ct-retention-outlook strong{display:block}.ct-retention-outlook strong{margin-top:5px;font-size:17px}.ct-retention-note{margin-bottom:15px;background:#edf7ff;color:#245779}.ct-retention-table-panel{margin-top:15px}.ct-retention-table-panel header>strong{font-size:18px;color:#173d70}.ct-due-status,.ct-release-status{display:inline-block;padding:4px 8px;border-radius:12px;font-size:14px;font-weight:700}.ct-due-status.is-due{background:#ffe5e8;color:#ad2639}.ct-due-status.is-upcoming{background:#fff1ce;color:#8a5c00}.ct-due-status.is-not_due{background:#e4f1ff;color:#236ba5}.ct-due-status.is-no_date{background:#eeeef1;color:#5f6470}.ct-due-status.is-closed,.ct-release-status.is-released{background:#dcf6ea;color:#087653}.ct-release-status.is-partial{background:#fff1ce;color:#8a5c00}.ct-release-status.is-held{background:#e9eef5;color:#445b73}.ct-retention-table-panel td small{display:block;margin-top:3px;color:#7a899a}@media(max-width:1200px){.ct-retention-kpis{grid-template-columns:repeat(3,1fr)}.ct-financial-report-filter.ct-retention-filter{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.ct-retention-kpis,.ct-retention-outlook>div,.ct-retention-context,.ct-financial-report-filter.ct-retention-filter{grid-template-columns:1fr}}</style>
@endpush
