@php
    $companyAddress = collect([$businessLocation?->landmark,$businessLocation?->city,$businessLocation?->state,$businessLocation?->country])->filter()->implode('، ');
    $logoSource = $business->logo && is_file(public_path('uploads/business_logos/'.$business->logo)) ? asset('uploads/business_logos/'.$business->logo) : null;
@endphp
<!doctype html><html lang="{{ app()->getLocale() }}" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@lang('construction::lang.subcontractor_statement') — {{ $selectedSubcontractor->supplier_business_name ?: $selectedSubcontractor->name }}</title><style>
@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box}body{margin:0;background:#eef3f8;color:#19334f;direction:rtl}.toolbar{display:flex;justify-content:center;padding:10px}.toolbar button{border:0;border-radius:8px;padding:9px 22px;background:#1769d2;color:#fff;font-weight:700}.page{width:279mm;min-height:190mm;margin:0 auto 10px;padding:8mm;background:#fff}.accent{height:5px;margin:-8mm -8mm 5mm;background:#1769d2}.header{width:100%;border-collapse:collapse;border-bottom:1px solid #dce5ef}.header td{padding:4px}.logo{width:22mm}.logo img{max-width:20mm;max-height:16mm}.company strong,.company span{display:block}.company strong{color:#174f8c}.contact{text-align:left;color:#697b90}.title{text-align:center;margin:4mm 0}.title h1{margin:0;color:#173d70}.title p{margin:2px;color:#74849a}.meta{display:grid;grid-template-columns:1.5fr 1.5fr 1fr;gap:6px;margin-bottom:4mm}.meta div,.kpis article,.summary{border:1px solid #dfe7ef;border-radius:8px}.meta div{padding:7px}.meta small,.meta strong{display:block}.meta small{color:#8492a4}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.kpis article{padding:9px;border-top:4px solid #1769d2}.kpis small,.kpis strong,.kpis span{display:block}.kpis small{color:#78889b}.kpis strong{margin:4px 0;color:#173d70;font-size:17px}.kpis span{font-size:10px}.summary{display:grid;grid-template-columns:repeat(6,1fr);gap:0;margin:7px 0;padding:6px}.summary div{padding:5px;border-left:1px solid #e4ebf2}.summary div:last-child{border:0}.summary span,.summary strong{display:block}.summary span{font-size:10px;color:#78889b}.statement{width:100%;border-collapse:collapse;table-layout:fixed;font-size:10px}.statement th,.statement td{padding:5px;border:1px solid #dbe4ed;text-align:center}.statement th{background:#174f8c;color:#fff}.statement td:nth-child(5){text-align:right}.statement tr:nth-child(even) td{background:#f7faff}.statement tfoot th{background:#eaf1f8;color:#173d70}.badge{display:inline-block;border-radius:9px;padding:2px 5px;background:#eaf1f8}.opening td{background:#fff7df!important;font-weight:700}.footer{display:flex;justify-content:space-between;margin-top:5mm;padding-top:2mm;border-top:1px solid #dce5ef;color:#8794a4}.signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:20mm;margin-top:12mm;text-align:center}.signatures div{padding-top:10mm;border-top:1px solid #789}@media print{body{background:#fff}.toolbar{display:none}.page{width:auto;margin:0;padding:0;min-height:auto}.accent{margin:0 0 5mm}}
@include('construction::partials.print_typography')</style></head><body>
<div class="toolbar"><button onclick="window.print()">@lang('construction::lang.print')</button></div>
<section class="page"><div class="accent"></div><table class="header"><tr>@if($logoSource)<td class="logo"><img src="{{ $logoSource }}"></td>@endif<td class="company"><strong class="print-company-name">{{ $business->name }}</strong><span>{{ $businessLocation?->name }}</span></td><td class="contact">{{ $companyAddress }}</td></tr></table>
<div class="title"><h1 class="print-document-title">@lang('construction::lang.subcontractor_statement')</h1><p>@lang('construction::lang.subcontractor_statement_print_subtitle')</p></div>
<div class="meta"><div><small>@lang('construction::lang.subcontractor')</small><strong>{{ $selectedSubcontractor->supplier_business_name ?: $selectedSubcontractor->name }}</strong></div><div><small>@lang('construction::lang.project')</small><strong>{{ $selectedProject ? $selectedProject->code.' — '.$selectedProject->name : __('construction::lang.statement_all_projects') }}</strong></div><div><small>@lang('construction::lang.report_period')</small><strong>{{ $fromDate ? @format_date($fromDate) : __('construction::lang.account_inception') }} — {{ @format_date($toDate) }}</strong></div></div>
<div class="kpis"><article><small>@lang('construction::lang.contracts_value')</small><strong>@include('construction::partials.money',['value'=>$statement['summary']['contracts_value']])</strong><span>{{ $statement['agreements_count'] }} @lang('construction::lang.agreements')</span></article><article><small>@lang('construction::lang.total_payable')</small><strong>@include('construction::partials.money',['value'=>$statement['summary']['payable']])</strong><span>{{ $statement['summary']['certificates_count'] }} @lang('construction::lang.approved_certificates')</span></article><article><small>@lang('construction::lang.paid_amount')</small><strong>@include('construction::partials.money',['value'=>$statement['summary']['paid']])</strong><span>@lang('construction::lang.recorded_payments_only')</span></article><article><small>@lang('construction::lang.current_balance')</small><strong>@include('construction::partials.money',['value'=>$statement['summary']['balance']])</strong><span>@lang('construction::lang.due_to_subcontractor')</span></article></div>
<div class="summary">@foreach(['gross'=>'approved_subcontract_work','deductions'=>'other_deductions','retention_original'=>'original_retention','retention_released'=>'released_retention','retention_remaining'=>'remaining_retention','opening_balance'=>'opening_balance'] as $key=>$label)<div><span>@lang('construction::lang.'.$label)</span><strong>@include('construction::partials.money',['value'=>$statement['summary'][$key]])</strong></div>@endforeach</div>
<table class="statement print-table"><thead><tr><th style="width:8%">@lang('construction::lang.date')</th><th style="width:10%">@lang('construction::lang.movement_type')</th><th style="width:11%">@lang('construction::lang.document_number')</th><th style="width:14%">@lang('construction::lang.project')</th><th>@lang('construction::lang.description')</th><th style="width:10%">@lang('construction::lang.debit_paid')</th><th style="width:10%">@lang('construction::lang.credit_due')</th><th style="width:10%">@lang('construction::lang.running_balance')</th></tr></thead><tbody>
@if($fromDate)<tr class="opening"><td>{{ @format_date($fromDate) }}</td><td colspan="6">@lang('construction::lang.opening_balance')</td><td>@include('construction::partials.money',['value'=>$statement['summary']['opening_balance']])</td></tr>@endif
@forelse($statement['movements'] as $movement)<tr><td>{{ @format_date($movement['date']) }}</td><td><span class="badge">@lang('construction::lang.statement_type_'.$movement['type'])</span></td><td dir="ltr">{{ $movement['number'] }}</td><td>{{ $movement['project'] ?: '—' }}</td><td>{{ $movement['description'] }}<br><small>{{ $movement['agreement'] }}</small></td><td>@include('construction::partials.money',['value'=>$movement['debit']])</td><td>@include('construction::partials.money',['value'=>$movement['credit']])</td><td><strong>@include('construction::partials.money',['value'=>$movement['balance']])</strong></td></tr>@empty<tr><td colspan="8">@lang('construction::lang.no_statement_movements')</td></tr>@endforelse
</tbody><tfoot><tr><th colspan="5">@lang('construction::lang.period_totals')</th><th>@include('construction::partials.money',['value'=>$statement['summary']['period_debit']])</th><th>@include('construction::partials.money',['value'=>$statement['summary']['period_credit']])</th><th>@include('construction::partials.money',['value'=>$statement['summary']['closing_balance']])</th></tr></tfoot></table>
<div class="signatures"><div>@lang('construction::lang.prepared_by')</div><div>@lang('construction::lang.accounting_signature')</div><div>@lang('construction::lang.subcontractor_signature')</div></div><div class="footer"><span>@lang('construction::lang.report_generated_at'): {{ @format_datetime(now()) }}</span><strong>@lang('construction::lang.closing_balance'): @include('construction::partials.money',['value'=>$statement['summary']['closing_balance']])</strong></div></section></body></html>
