@extends('construction::layouts.module')
@section('title', __('construction::lang.import_review'))
@section('module_content')
<section class="content">
    <div class="row"><div class="col-md-4"><div class="info-box"><span class="info-box-icon bg-aqua"><i class="fa fa-list-ol"></i></span><div class="info-box-content"><span class="info-box-text">@lang('construction::lang.import_rows')</span><span class="info-box-number">{{ $batch->row_count }}</span></div></div></div><div class="col-md-4"><div class="info-box"><span class="info-box-icon bg-{{ $batch->error_count ? 'red' : 'green' }}"><i class="fa fa-{{ $batch->error_count ? 'exclamation-triangle' : 'check' }}"></i></span><div class="info-box-content"><span class="info-box-text">@lang('construction::lang.import_errors')</span><span class="info-box-number">{{ $batch->error_count }}</span></div></div></div><div class="col-md-4"><div class="info-box"><span class="info-box-icon bg-purple"><i class="fa fa-coins"></i></span><div class="info-box-content"><span class="info-box-text">@lang('construction::lang.import_total')</span><span class="info-box-number">@include('construction::partials.money', ['value' => collect($batch->rows_json)->sum('sales_total')])</span></div></div></div></div>
    <div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">{{ $batch->file_name }}</h3><div class="box-tools"><a href="{{ route('construction.projects.boq.show', [$project->id,$version->id]) }}" class="btn btn-default btn-sm">@lang('construction::lang.back_to_boq')</a>@if($batch->error_count === 0)<form method="POST" action="{{ route('construction.projects.boq.import.commit', [$project->id,$version->id,$batch->token]) }}" style="display:inline">@csrf<button class="btn btn-success btn-sm"><i class="fa fa-check"></i> @lang('construction::lang.confirm_import')</button></form>@endif</div></div>
        <div class="box-body">@if($batch->error_count)<div class="callout callout-danger"><p>@lang('construction::lang.import_fix_errors')</p></div>@else<div class="callout callout-success"><p>@lang('construction::lang.import_ready')</p></div>@endif
            <div class="table-responsive"><table class="table table-bordered table-hover"><thead><tr><th>#</th><th>@lang('construction::lang.boq_row_type')</th><th>@lang('construction::lang.boq_code')</th><th>@lang('construction::lang.boq_description')</th><th>@lang('construction::lang.boq_parent_section')</th><th>@lang('construction::lang.unit')</th><th>@lang('construction::lang.contract_quantity')</th><th>@lang('construction::lang.sales_unit_price')</th><th>@lang('construction::lang.sales_total')</th><th>@lang('construction::lang.import_errors')</th></tr></thead><tbody>
                @foreach($batch->rows_json as $row)<tr class="{{ count($row['errors']) ? 'danger' : '' }}"><td>{{ $row['row_number'] }}</td><td>@lang('construction::lang.'.($row['row_type']==='section'?'boq_section':'boq_item'))</td><td><strong>{{ $row['code'] }}</strong></td><td>{{ $row['description'] }}</td><td>{{ $row['parent_code'] ?: '—' }}</td><td>{{ $row['unit'] ?: '—' }}</td><td>{{ @format_quantity((float)$row['quantity']) }}</td><td>@include('construction::partials.money', ['value' => $row['unit_price']])</td><td>@include('construction::partials.money', ['value' => $row['sales_total']])</td><td>@forelse($row['errors'] as $error)<div class="text-danger"><i class="fa fa-times-circle"></i> {{ $error }}</div>@empty<span class="text-success"><i class="fa fa-check"></i> @lang('construction::lang.valid_row')</span>@endforelse</td></tr>@endforeach
            </tbody></table></div>
        </div>
    </div>
</section>
@endsection
