@php
$supplierName = $contract->subcontractor->supplier_business_name ?: $contract->subcontractor->name;
$logoSource = !empty($business->logo) ? public_path('uploads/business_logos/'.$business->logo) : null;
if ($logoSource && !is_file($logoSource)) $logoSource = null;
$companyAddress = collect([$businessLocation?->landmark, $businessLocation?->city, $businessLocation?->state, $businessLocation?->country])->filter()->implode('، ');
@endphp
<!doctype html><html lang="{{ app()->getLocale() }}" dir="rtl"><head><meta charset="utf-8"><title>{{ $certificate->number }}</title><style>
*{box-sizing:border-box}body{margin:0;background:#eef2f6;color:#18324f;font-family:Arial,sans-serif}.toolbar{display:flex;gap:8px;justify-content:center;padding:14px}.toolbar button{padding:9px 22px;border:0;border-radius:7px;background:#1769d2;color:#fff;font-weight:700}.page{position:relative;width:210mm;min-height:287mm;margin:0 auto 24px;padding:14mm;background:#fff;box-shadow:0 10px 40px #cbd4df}.accent{height:5px;margin:-14mm -14mm 9mm;background:#174f8c}.header{width:100%;margin-bottom:8mm}.header td{vertical-align:middle}.logo img{max-width:45mm;max-height:20mm}.company strong,.company span{display:block}.company strong{font-size:19px}.address{text-align:left;color:#697b8f;font-size:11px}.title{text-align:center;margin-bottom:7mm}.title h1{margin:0 0 8px;font-size:23px;color:#174f8c}.number{display:inline-block;padding:5px 14px;border-radius:16px;background:#eaf3ff;font-weight:800;direction:ltr}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-bottom:7mm}.meta div{padding:9px;border:1px solid #dfe7ef;border-radius:7px}.meta small,.meta strong{display:block}.meta small{color:#7e8c9d;font-size:10px;margin-bottom:3px}.items{width:100%;border-collapse:collapse;font-size:10px}.items th,.items td{padding:7px 5px;border:1px solid #d9e2eb;text-align:center}.items th{background:#174f8c;color:#fff}.items td.desc{text-align:right}.summary{width:78mm;margin:7mm 0 0 auto;border-collapse:collapse}.summary td{padding:7px;border-bottom:1px solid #e1e7ee}.summary td:last-child{text-align:left;font-weight:800}.summary tr.net td{background:#eaf3ff;color:#174f8c;font-size:13px}.notes{margin-top:6mm;padding:9px;border:1px solid #dfe7ef;border-radius:7px;font-size:10px}.signatures{display:grid;grid-template-columns:repeat(4,1fr);gap:8mm;margin-top:18mm;text-align:center;font-size:11px;font-weight:700}.signatures div{padding-top:20mm;border-top:1px solid #7b8794}.watermark{position:absolute;top:46%;right:17%;transform:rotate(-28deg);font-size:54px;color:rgba(214,56,56,.09);font-weight:900}.status{padding:4px 10px;border-radius:13px;font-size:10px}.status.approved{background:#dff7ed;color:#13845c}.status.draft{background:#fff0ce;color:#9b6700}@media print{body{background:#fff}.toolbar{display:none}.page{margin:0;box-shadow:none;width:auto;min-height:auto}@page{size:A4;margin:0}}
@include('construction::partials.print_typography')</style></head><body>
<div class="toolbar"><button onclick="window.print()">@lang('construction::lang.print_document')</button><button onclick="window.close()">@lang('construction::lang.close_preview')</button></div>
<main class="page"><div class="accent"></div>@if($certificate->status !== 'approved')<div class="watermark">@lang('construction::lang.draft_unapproved')</div>@endif
<table class="header"><tr>@if($logoSource)<td class="logo"><img src="{{ $logoSource }}"></td>@endif<td class="company"><strong>{{ $business->name }}</strong><span>{{ $businessLocation?->name }}</span></td><td class="address">{{ $companyAddress }}</td></tr></table>
<div class="title"><h1>@lang('construction::lang.subcontract_certificate_print_title')</h1><span class="number">{{ $certificate->number }}</span> <span class="status {{ $certificate->status }}">@lang('construction::lang.'.$certificate->status)</span></div>
<div class="meta"><div><small>@lang('construction::lang.subcontractor')</small><strong>{{ $supplierName }}</strong></div><div><small>@lang('construction::lang.project')</small><strong>{{ $contract->project->code }} — {{ $contract->project->name }}</strong></div><div><small>@lang('construction::lang.agreement_number')</small><strong>{{ $contract->number }}</strong></div><div><small>@lang('construction::lang.certificate_date')</small><strong>{{ @format_date($certificate->certificate_date) }}</strong></div></div>
<table class="items"><thead><tr><th>#</th><th>@lang('construction::lang.work_description')</th><th>@lang('construction::lang.contract_quantity')</th><th>@lang('construction::lang.previous_quantity')</th><th>@lang('construction::lang.current_quantity')</th><th>@lang('construction::lang.cumulative_quantity')</th><th>@lang('construction::lang.current_value')</th></tr></thead><tbody>@foreach($certificate->items as $line)<tr><td>{{ $loop->iteration }}</td><td class="desc">{{ $line->description }}</td><td>{{ @num_format($line->contract_quantity) }}</td><td>{{ @num_format($line->previous_quantity) }}</td><td>{{ @num_format($line->current_quantity) }}</td><td>{{ @num_format($line->cumulativeQuantity()) }}</td><td>@include('construction::partials.money',['value'=>$line->current_value])</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>@lang('construction::lang.gross_certificate')</td><td>@include('construction::partials.money',['value'=>$certificate->gross_value])</td></tr><tr><td>@lang('construction::lang.retention_value') ({{ @num_format($certificate->retention_percent) }}%)</td><td>@include('construction::partials.money',['value'=>$certificate->retention_value])</td></tr><tr><td>@lang('construction::lang.other_deductions')</td><td>@include('construction::partials.money',['value'=>$certificate->other_deductions])</td></tr><tr class="net"><td>@lang('construction::lang.net_certificate_due')</td><td>@include('construction::partials.money',['value'=>$certificate->net_value])</td></tr></table>
@if($certificate->notes)<div class="notes"><strong>@lang('construction::lang.notes'):</strong> {{ $certificate->notes }}</div>@endif
<div class="signatures"><div>@lang('construction::lang.prepared_by')</div><div>@lang('construction::lang.site_engineer')</div><div>@lang('construction::lang.project_manager')</div><div>@lang('construction::lang.financial_approval')</div></div>
</main>@if($autoPrint)<script>window.addEventListener('load',function(){window.print()})</script>@endif</body></html>
