@extends('construction::layouts.module')
@section('title', __('construction::lang.customer_certificates'))
@section('module_css')
    @include('construction::certificates.styles')
@endsection
@section('module_content')
<section class="content ct-certificate-page">
    <div class="ct-measurement-heading"><div><span><i class="fa fa-file-invoice-dollar"></i> @lang('construction::lang.customer_certificates')</span><h2>@lang('construction::lang.customer_certificates')</h2><p>@lang('construction::lang.certificates_description')</p></div><div class="ct-measurement-heading__actions"><a class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.measurements.index', $project->id) }}">@lang('construction::lang.measurements')</a><a class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.show', $project->id) }}">@lang('construction::lang.project_details')</a></div></div>
    @if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
    <div id="ct-quick-list">
        <article class="ct-measurement-card"><header class="ct-measurement-card__header"><span class="ct-measurement-card__icon"><i class="fa fa-list"></i></span><div><h3>@lang('construction::lang.customer_certificates')</h3><p>{{ $project->name }}</p></div></header><div class="ct-measurement-table-wrap"><table class="ct-measurement-table ct-certificate-list"><thead><tr><th>@lang('construction::lang.certificate_number')</th><th>@lang('construction::lang.certificate_date')</th><th>@lang('construction::lang.current_approved_gross')</th><th>@lang('construction::lang.net_due')</th><th>@lang('construction::lang.certificate_status')</th><th></th></tr></thead><tbody>@forelse($certificates as $certificate)<tr><td><strong>{{ $certificate->number }}</strong></td><td>{{ @format_date($certificate->certificate_date) }}</td><td>@include('construction::partials.money', ['value' => $certificate->current_approved_gross ?: $certificate->current_submitted_gross])</td><td><strong>@include('construction::partials.money', ['value' => $certificate->net_due])</strong></td><td><span class="ct-measurement-status ct-measurement-status--{{ $certificate->status }}">@lang('construction::lang.'.$certificate->status)</span></td><td><a data-ct-workspace class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.certificates.show', [$project->id, $certificate->id]) }}">@lang('construction::lang.open_certificate')</a></td></tr>@empty<tr><td colspan="6">@lang('construction::lang.no_certificates_yet')</td></tr>@endforelse</tbody></table></div></article>
    @can('construction.certificate.manage')<div style="margin-top:16px"><button type="button" class="ct-measurement-button ct-measurement-button--success" data-toggle="modal" data-target="#ct-certificate-create" {{ !$contract || $contract->status !== 'active' || $unbilledCount < 1 ? 'disabled' : '' }}><i class="fa fa-plus"></i> @lang('construction::lang.new_certificate')</button>@if(!$contract || $contract->status !== 'active')<p class="text-warning">@lang('construction::lang.certificate_requires_active_contract')</p>@endif</div>@endcan
    </div>
    <div id="ct-quick-workspace"></div>
</section>
@can('construction.certificate.manage')<div class="modal fade ct-quick-modal" id="ct-certificate-create" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content">
    <form method="POST" action="{{ route('construction.projects.certificates.store', $project->id) }}" data-ct-quick-create>@csrf<div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="@lang('messages.close')"><span aria-hidden="true">&times;</span></button><h4 class="modal-title">@lang('construction::lang.new_certificate')</h4></div><div class="modal-body"><div class="alert alert-danger ct-quick-errors" role="alert"></div><div class="ct-certificate-form">
            <div><label>@lang('construction::lang.certificate_number')</label><input class="form-control" value="{{ $nextNumber }}" readonly></div>
            <div><label>@lang('construction::lang.project_name')</label><input class="form-control" value="{{ $project->name }}" readonly></div>
            <div><label>@lang('construction::lang.contract_number')</label><input class="form-control" value="{{ $contract?->contract_number ?: '—' }}" readonly></div>
            <div><label>@lang('construction::lang.measurement_number') *</label><select name="measurement_id" class="form-control" required><option value="">@lang('construction::lang.select_approved_measurement')</option>@foreach($measurements as $measurement)<option value="{{ $measurement->id }}" {{ (string) old('measurement_id', $selectedMeasurement?->id) === (string) $measurement->id ? 'selected' : '' }}>{{ $measurement->number }}</option>@endforeach</select></div>
            <div><label>@lang('construction::lang.certificate_date') *</label><input name="certificate_date" class="form-control ct-date-picker" readonly required value="{{ old('certificate_date', @format_date(now())) }}"></div>
            <div class="ct-certificate-two"><div><label>@lang('construction::lang.period_from')</label><input name="period_from" class="form-control ct-date-picker" readonly value="{{ old('period_from') }}"></div><div><label>@lang('construction::lang.period_to')</label><input name="period_to" class="form-control ct-date-picker" readonly value="{{ old('period_to') }}"></div></div>
            <div><label>@lang('construction::lang.retention_percent')</label><input class="form-control" value="{{ @num_format($retentionPercent) }}%" readonly></div>
            <div><label>@lang('construction::lang.retention_due_date')</label><input name="retention_due_date" class="form-control ct-date-picker" readonly value="{{ old('retention_due_date') }}"><small>@lang('construction::lang.retention_due_date_hint')</small></div>
            @if((float) ($contract?->advance_payment_value ?? 0) > 0)<div><label>@lang('construction::lang.advance_recovery_value')</label><input name="advance_recovery_value" class="form-control input_number" value="{{ old('advance_recovery_value', @num_format(0)) }}"><small>@lang('construction::lang.original_advance'): @include('construction::partials.money', ['value' => (float) $contract->advance_payment_value]) · @lang('construction::lang.previously_recovered'): @include('construction::partials.money', ['value' => $previousRecovered]) · @lang('construction::lang.advance_remaining'): @include('construction::partials.money', ['value' => max(0, (float) $contract->advance_payment_value - $previousRecovered)])</small></div>@endif
            <div><label>@lang('construction::lang.other_deductions_value')</label><input name="other_deductions_value" class="form-control input_number" value="{{ old('other_deductions_value', @num_format(0)) }}"></div>
        </div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">@lang('messages.cancel')</button><button class="ct-measurement-button ct-measurement-button--success" type="submit" {{ !$contract || $contract->status !== 'active' || $unbilledCount < 1 ? 'disabled' : '' }}><i class="fa fa-plus"></i> @lang('construction::lang.new_certificate')</button></div></form>
    </div></div></div>@endcan
@endsection
@include('construction::partials.quick_create')
@if($selectedMeasurement && $unbilledCount > 0)
@push('ct_quick_js')
<script>jQuery(function($){$('#ct-certificate-create').modal('show');});</script>
@endpush
@endif
