@extends('construction::layouts.module')
@section('title', $certificate->number)
@section('module_css')
    @include('construction::certificates.styles')
@endsection
@section('module_content')
@php
    $approved = in_array($certificate->status, ['approved', 'posted', 'paid', 'partially_approved']);
    $current = (float) ($approved ? $certificate->current_approved_gross : $certificate->current_submitted_gross);
    $cumulative = (float) $certificate->previous_gross + $current;
    $contractValue = (float) ($certificate->contract?->original_value ?: $certificate->boqVersion?->sales_total);
    $progress = $contractValue > 0 ? 100 * $cumulative / $contractValue : 0;
    $advance = (float) ($certificate->contract?->advance_payment_value ?? 0);
@endphp
<section class="content ct-certificate-page">
    <div class="ct-measurement-heading"><div><span><a href="{{ route('construction.projects.show', $project->id) }}">{{ $project->name }}</a> / <a href="{{ route('construction.projects.certificates.index', $project->id) }}">@lang('construction::lang.customer_certificates')</a> / {{ $certificate->number }}</span><h2>{{ $certificate->number }} <span class="ct-measurement-status ct-measurement-status--{{ $certificate->status }}">@lang('construction::lang.'.$certificate->status)</span></h2><p>{{ $project->name }} · {{ $certificate->contract?->contract_number ?: '—' }} · {{ @format_date($certificate->certificate_date) }}</p></div><div class="ct-measurement-heading__actions"><a class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.certificates.index', $project->id) }}">@lang('construction::lang.back_to_certificates')</a><a class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.certificates.preview', [$project->id, $certificate->id]) }}" target="_blank">@lang('construction::lang.preview')</a>@if($approved)<a class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.certificates.print', [$project->id, $certificate->id]) }}" target="_blank">@lang('construction::lang.print')</a><a class="ct-measurement-button ct-measurement-button--soft" href="{{ route('construction.projects.certificates.pdf', [$project->id, $certificate->id]) }}">PDF</a>@endif</div></div>
    <article class="ct-measurement-card"><header class="ct-measurement-card__header"><span class="ct-measurement-card__icon"><i class="fa fa-info-circle"></i></span><div><h3>@lang('construction::lang.certificate_information')</h3></div></header><div class="ct-measurement-info-grid"><div><small>@lang('construction::lang.certificate_number')</small><strong>{{ $certificate->number }}</strong></div><div><small>@lang('construction::lang.project_name')</small><strong>{{ $project->name }}</strong></div><div><small>@lang('construction::lang.contract_number')</small><strong>{{ $certificate->contract?->contract_number ?: '—' }}</strong></div><div><small>@lang('construction::lang.measurement_number')</small><strong>{{ $certificate->measurement?->number ?: '—' }}</strong></div><div><small>@lang('construction::lang.certificate_date')</small><strong>{{ @format_date($certificate->certificate_date) }}</strong></div><div><small>@lang('construction::lang.period_from')</small><strong>@if($certificate->period_from){{ @format_date($certificate->period_from) }}@else—@endif</strong></div><div><small>@lang('construction::lang.period_to')</small><strong>@if($certificate->period_to){{ @format_date($certificate->period_to) }}@else—@endif</strong></div></div></article>
    <div class="ct-certificate-summary"><div><small>@lang('construction::lang.previous_gross')</small><strong>@include('construction::partials.money', ['value' => $certificate->previous_gross])</strong></div><div><small>@lang('construction::lang.current_work_value')</small><strong>@include('construction::partials.money', ['value' => $current])</strong></div><div><small>@lang('construction::lang.cumulative_gross')</small><strong>@include('construction::partials.money', ['value' => $cumulative])</strong></div><div><small>@lang('construction::lang.completion_percent')</small><strong>{{ @num_format($progress) }}%</strong></div><div><small>@lang('construction::lang.total_deductions')</small><strong>@include('construction::partials.money', ['value' => (float) $certificate->retention_value + (float) $certificate->advance_recovery_value + (float) $certificate->other_deductions_value])</strong></div><div class="ct-certificate-summary__net"><small>@lang('construction::lang.net_due')</small><strong>@include('construction::partials.money', ['value' => $certificate->net_due])</strong></div></div>
    <article class="ct-measurement-card"><header class="ct-measurement-card__header"><span class="ct-measurement-card__icon"><i class="fa fa-list-ol"></i></span><div><h3>@lang('construction::lang.certificate_items')</h3><p>@lang('construction::lang.certificate_items_auto_hint')</p></div></header><div class="ct-measurement-table-wrap"><table class="ct-measurement-table ct-certificate-table"><thead><tr><th>@lang('construction::lang.boq_code')</th><th>@lang('construction::lang.boq_description')</th><th>@lang('construction::lang.unit')</th><th>@lang('construction::lang.contract_quantity')</th><th>@lang('construction::lang.previous_quantity')</th><th>@lang('construction::lang.current_quantity')</th><th>@lang('construction::lang.cumulative_quantity')</th><th>@lang('construction::lang.sales_unit_price')</th><th>@lang('construction::lang.current_work_value')</th></tr></thead><tbody>@foreach($certificate->items as $item)@php $quantity = (float) ($approved ? $item->approved_quantity : $item->submitted_quantity); $amount = (float) ($approved ? $item->approved_amount : $item->submitted_amount); @endphp<tr><td><strong class="ct-measurement-code">{{ $item->boqItem->code }}</strong></td><td class="ct-certificate-description">{{ $item->boqItem->description }}</td><td>{{ $item->boqItem->unit ?: '—' }}</td><td>{{ @format_quantity((float) $item->boqItem->contract_quantity) }}</td><td>{{ @format_quantity((float) $item->previous_quantity) }}</td><td><strong>{{ @format_quantity($quantity) }}</strong></td><td>{{ @format_quantity((float) $item->previous_quantity + $quantity) }}</td><td>@include('construction::partials.money', ['value' => $item->unit_price])</td><td><strong>@include('construction::partials.money', ['value' => $amount])</strong></td></tr>@endforeach</tbody></table></div></article>
    <div class="ct-certificate-bottom"><article class="ct-measurement-card"><header class="ct-measurement-card__header"><span class="ct-measurement-card__icon"><i class="fa fa-calculator"></i></span><div><h3>@lang('construction::lang.deductions_and_adjustments')</h3></div></header><div class="ct-certificate-financial"><div><span>@lang('construction::lang.current_work_value')</span><strong>@include('construction::partials.money', ['value' => $current])</strong></div><div><span>@lang('construction::lang.retention_value') {{ @num_format((float) $certificate->retention_percent) }}%</span><strong>@if((float)$certificate->retention_value > 0)− @endif @include('construction::partials.money', ['value' => $certificate->retention_value])</strong></div>@if($advance > 0)<div><span>@lang('construction::lang.original_advance')</span><strong>@include('construction::partials.money', ['value' => $advance])</strong></div><div><span>@lang('construction::lang.previously_recovered')</span><strong>@include('construction::partials.money', ['value' => (float) $recoveredBefore])</strong></div><div><span>@lang('construction::lang.advance_recovery_value')</span><strong>@if((float)$certificate->advance_recovery_value > 0)− @endif @include('construction::partials.money', ['value' => $certificate->advance_recovery_value])</strong></div><div><span>@lang('construction::lang.advance_remaining')</span><strong>@include('construction::partials.money', ['value' => max(0, $advance - (float) $recoveredBefore - (float) $certificate->advance_recovery_value)])</strong></div>@endif<div><span>@lang('construction::lang.other_deductions_value')</span><strong>@if((float)$certificate->other_deductions_value > 0)− @endif @include('construction::partials.money', ['value' => $certificate->other_deductions_value])</strong></div><div><span>@lang('construction::lang.tax_value') {{ @num_format((float) $certificate->tax_percent) }}%</span><strong>@if((float)$certificate->tax_value > 0)+ @endif @include('construction::partials.money', ['value' => $certificate->tax_value])</strong></div><div class="ct-certificate-financial__net"><span>@lang('construction::lang.net_due')</span><strong>@include('construction::partials.money', ['value' => $certificate->net_due])</strong></div></div></article>
    <article class="ct-measurement-card"><header class="ct-measurement-card__header"><span class="ct-measurement-card__icon"><i class="fa fa-check-circle"></i></span><div><h3>@lang('construction::lang.certificate_next_step')</h3></div></header><div class="ct-certificate-actions">@if(in_array($certificate->status, ['draft', 'submitted']))<p>@lang('construction::lang.certificate_review_hint')</p>@can('construction.certificate.approve')<form method="POST" action="{{ route('construction.projects.certificates.approve', [$project->id, $certificate->id]) }}">@csrf<button class="ct-measurement-button ct-measurement-button--success"><i class="fa fa-check"></i> @lang('construction::lang.approve_certificate')</button></form>@endcan @can('construction.certificate.manage')<form method="POST" action="{{ route('construction.projects.certificates.cancel', [$project->id, $certificate->id]) }}">@csrf<button class="ct-measurement-button ct-measurement-button--soft">@lang('construction::lang.cancel_certificate')</button></form>@endcan @elseif($approved)<p><i class="fa fa-lock"></i> @lang('construction::lang.approved_certificate_locked')</p>@if($certificate->invoice && $certificate->invoice->status === 'final')<div class="ct-certificate-invoice-link"><strong>@lang('construction::lang.invoice_created_with_number', ['number' => $certificate->invoice->invoice_no])</strong><a class="view_invoice_url ct-measurement-button ct-measurement-button--primary" href="{{ url('/sells/'.$certificate->invoice->id).'?construction=1' }}"><i class="fa fa-external-link-alt"></i> @lang('construction::lang.open_invoice')</a></div>@elseif(auth()->user()->can('sell.create') || auth()->user()->can('direct_sell.access'))<form method="POST" action="{{ route('construction.projects.certificates.invoice', [$project->id, $certificate->id]) }}" id="ct-create-certificate-invoice">@csrf<button class="ct-measurement-button ct-measurement-button--primary"><i class="fa fa-file-invoice"></i> @lang('construction::lang.create_invoice_from_certificate')</button></form>@endif @else<p>@lang('construction::lang.cancelled')</p>@endif</div></article></div>
</section>
@endsection

@section('module_javascript')
<script>
$(function () {
    $('#ct-create-certificate-invoice').on('submit', function () {
        $(this).find('button[type="submit"]').prop('disabled', true).prepend('<i class="fa fa-spinner fa-spin"></i> ');
    });
});
</script>
@endsection
