@extends('construction::layouts.module')
@section('title', $quote->number)
@section('module_css')@include('construction::quotes.styles')@endsection

@section('module_content')
<section class="ct-quote-page">
    <header class="ct-quote-heading"><div><span class="ct-quote-eyebrow">@lang('construction::lang.quote_first_step') · {{ $quote->number }}</span><h2>{{ $quote->title }}</h2><p>{{ $quote->customer?->supplier_business_name ?: $quote->customer?->name }} · {{ @format_date($quote->quote_date) }}</p></div><div class="ct-quote-total"><small>@lang('construction::lang.quote_total')</small><strong>@include('construction::partials.money', ['value' => $quote->total])</strong></div></header>
    <div class="ct-quote-actions" style="margin-bottom:18px">
        <span class="ct-quote-badge ct-quote-badge--{{ $quote->project_id ? 'converted' : $quote->status }}">@lang('construction::lang.quote_status_'.($quote->project_id ? 'converted' : $quote->status))</span>
        @if(in_array($quote->status, ['draft', 'sent'], true) && !$quote->project_id)@can('construction.project.create')<button class="ct-quote-btn" type="button" data-toggle="modal" data-target="#ct-quote-edit"><i class="fa fa-pen"></i> @lang('construction::lang.edit_quote')</button>@endcan @endif
        @if(!$quote->project_id)@can('construction.boq.approve')<button class="ct-quote-btn" type="button" data-toggle="modal" data-target="#ct-quote-status"><i class="fa fa-check-circle"></i> @lang('construction::lang.change_quote_status')</button>@endcan @endif
        @if($quote->status === 'accepted' && !$quote->project_id)@can('construction.project.create')<a class="ct-quote-btn ct-quote-btn--success" href="{{ route('construction.projects.index', ['quote_id' => $quote->id]) }}"><i class="fa fa-building"></i> @lang('construction::lang.create_project_from_quote')</a>@endcan @endif
        <a class="ct-quote-btn" href="{{ route('construction.quotes.preview', $quote->id) }}" target="_blank"><i class="fa fa-eye"></i> @lang('construction::lang.preview')</a>
        <a class="ct-quote-btn" href="{{ route('construction.quotes.print', $quote->id) }}" target="_blank"><i class="fa fa-print"></i> @lang('construction::lang.print')</a>
        <a class="ct-quote-btn" href="{{ route('construction.quotes.pdf', $quote->id) }}"><i class="fa fa-file-pdf"></i> PDF</a>
        <a class="ct-quote-btn" href="{{ route('construction.quotes.index') }}"><i class="fa fa-arrow-right"></i> @lang('construction::lang.all_quotes')</a>
    </div>
    @if($quote->project)<div class="ct-quote-notice ct-quote-notice--success"><i class="fa fa-check-circle"></i> @lang('construction::lang.quote_converted_to', ['code' => $quote->project->code]) <a href="{{ route('construction.projects.show', $quote->project->id) }}" class="ct-quote-btn ct-quote-btn--success" style="margin-right:12px">@lang('construction::lang.open_project')</a></div>@elseif($quote->status === 'accepted')<div class="ct-quote-notice">@lang('construction::lang.quote_ready_to_convert')</div>@endif
    <div class="ct-quote-card"><h3>@lang('construction::lang.quote_details')</h3><div class="ct-quote-facts">
        <div class="ct-quote-fact"><small>@lang('construction::lang.quote_number')</small><strong>{{ $quote->number }}</strong></div>
        <div class="ct-quote-fact"><small>@lang('construction::lang.quote_date')</small><strong>{{ @format_date($quote->quote_date) }}</strong></div>
        <div class="ct-quote-fact"><small>@lang('construction::lang.customer')</small><strong>{{ $quote->customer?->supplier_business_name ?: $quote->customer?->name }}</strong></div>
        <div class="ct-quote-fact"><small>@lang('construction::lang.quote_validity_days')</small><strong>{{ $quote->validity_days }} @lang('construction::lang.days')</strong></div>
    </div>@if($quote->notes)<p>{{ $quote->notes }}</p>@endif</div>
    <div class="ct-quote-card"><h3>@lang('construction::lang.quote_items')</h3><div class="ct-quote-table-wrap"><table class="ct-quote-table"><thead><tr><th>@lang('construction::lang.boq_code')</th><th>@lang('construction::lang.boq_description')</th><th>@lang('construction::lang.unit')</th><th class="ct-quote-num">@lang('construction::lang.quantity')</th><th class="ct-quote-num">@lang('construction::lang.unit_price')</th><th class="ct-quote-num">@lang('construction::lang.total')</th>@if(in_array($quote->status, ['draft','sent'], true) && !$quote->project_id)<th></th>@endif</tr></thead><tbody>
        @forelse($quote->items as $item)<tr><td>{{ $item->code }}</td><td>{{ $item->description }}</td><td>{{ $item->unit }}</td><td class="ct-quote-num">{{ @format_quantity((float)$item->quantity) }}</td><td class="ct-quote-num">@include('construction::partials.money', ['value' => $item->unit_price])</td><td class="ct-quote-num"><strong>@include('construction::partials.money', ['value' => $item->total])</strong></td>@if(in_array($quote->status, ['draft','sent'], true) && !$quote->project_id)<td>@can('construction.boq.manage')<button type="button" class="btn btn-xs btn-primary" data-toggle="modal" data-target="#ct-quote-item-{{ $item->id }}"><i class="fa fa-edit"></i></button> <form method="POST" action="{{ route('construction.quotes.items.destroy', [$quote->id, $item->id]) }}" style="display:inline" onsubmit="return confirm('{{ __('construction::lang.delete_item_confirmation') }}')">@csrf @method('DELETE')<button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button></form>@endcan</td>@endif</tr>
        @empty<tr><td colspan="7"><div class="ct-quote-empty"><i class="fa fa-list-ul"></i>@lang('construction::lang.quote_items_empty')</div></td></tr>@endforelse
        </tbody><tfoot><tr><td colspan="5">@lang('construction::lang.quote_total')</td><td class="ct-quote-num">@include('construction::partials.money', ['value' => $quote->total])</td>@if(in_array($quote->status, ['draft','sent'], true) && !$quote->project_id)<td></td>@endif</tr></tfoot></table></div></div>
    @if(in_array($quote->status, ['draft','sent'], true) && !$quote->project_id)@can('construction.boq.manage')
    <div class="ct-quote-card" id="quote-items"><h3>@lang('construction::lang.add_quote_items')</h3><p class="text-muted">@lang('construction::lang.quote_items_hint')</p><form method="POST" action="{{ route('construction.quotes.items.store', $quote->id) }}">@csrf<div class="ct-quote-table-wrap"><table class="ct-quote-entry"><thead><tr><th>@lang('construction::lang.boq_code')</th><th>@lang('construction::lang.boq_description')</th><th>@lang('construction::lang.unit')</th><th>@lang('construction::lang.quantity')</th><th>@lang('construction::lang.unit_price')</th><th>@lang('construction::lang.notes')</th><th>@lang('construction::lang.total')</th><th></th></tr></thead><tbody id="ct-quote-entry-rows"></tbody></table></div><div class="ct-quote-form-footer"><button class="ct-quote-btn" id="ct-quote-add-row" type="button"><i class="fa fa-plus"></i> @lang('construction::lang.add_row')</button><button class="ct-quote-btn ct-quote-btn--primary" type="submit"><i class="fa fa-save"></i> @lang('construction::lang.save_all_items')</button></div></form></div>
    <template id="ct-quote-row-template"><tr><td><input class="form-control" name="items[__INDEX__][code]" maxlength="60" placeholder="ITM-001"></td><td><input class="form-control ct-quote-wide" name="items[__INDEX__][description]" maxlength="500" required></td><td><select class="form-control" name="items[__INDEX__][unit_id]" required><option value="">@lang('construction::lang.choose')</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->actual_name }} ({{ $unit->short_name }})</option>@endforeach</select></td><td><input class="form-control ct-quote-qty" type="number" step="0.0001" min="0.0001" name="items[__INDEX__][quantity]" value="1" required></td><td><input class="form-control ct-quote-price" type="number" step="0.0001" min="0" name="items[__INDEX__][unit_price]" value="0" required></td><td><input class="form-control" name="items[__INDEX__][notes]" maxlength="1000"></td><td><span class="print-money print-money--{{ session('business.currency_symbol_placement') === 'before' ? 'before' : 'after' }}">@if(session('business.currency_symbol_placement') === 'before')@include('construction::partials.money_symbol', ['money' => \Modules\Construction\Support\CurrencyFormatter::parts(0), 'isSaudiRiyal' => strtoupper((string) session('currency.code')) === 'SAR', 'symbolSource' => asset('img/saudi-riyal-new.svg')])@endif<output>0</output>@if(session('business.currency_symbol_placement') !== 'before')@include('construction::partials.money_symbol', ['money' => \Modules\Construction\Support\CurrencyFormatter::parts(0), 'isSaudiRiyal' => strtoupper((string) session('currency.code')) === 'SAR', 'symbolSource' => asset('img/saudi-riyal-new.svg')])@endif</span></td><td><button class="btn btn-xs btn-default ct-quote-remove-row" type="button"><i class="fa fa-times"></i></button></td></tr></template>
    @endcan @endif
</section>
    @if(in_array($quote->status, ['draft', 'sent'], true) && !$quote->project_id)@can('construction.project.create')<div class="modal fade ct-quote-modal" id="ct-quote-edit" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('construction.quotes.update', $quote->id) }}">@csrf @method('PUT')<div class="modal-header"><button class="close" type="button" data-dismiss="modal">&times;</button><h4 class="modal-title">@lang('construction::lang.edit_quote')</h4></div><div class="modal-body"><div class="form-group"><label>@lang('construction::lang.quote_date')</label><input type="date" name="quote_date" class="form-control" value="{{ $quote->quote_date->toDateString() }}" required></div><div class="form-group"><label>@lang('construction::lang.customer')</label><select name="customer_id" class="form-control" required>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected($customer->id === $quote->customer_id)>{{ $customer->supplier_business_name ?: $customer->name }}</option>@endforeach</select></div><div class="form-group"><label>@lang('construction::lang.quote_title')</label><input name="title" class="form-control" maxlength="190" value="{{ $quote->title }}" required></div><div class="form-group"><label>@lang('construction::lang.quote_validity_days')</label><input type="number" name="validity_days" class="form-control" min="1" max="365" value="{{ $quote->validity_days }}" required></div><div class="form-group"><label>@lang('construction::lang.quote_notes')</label><textarea name="notes" class="form-control" rows="3">{{ $quote->notes }}</textarea></div></div><div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">@lang('messages.cancel')</button><button class="btn btn-primary" type="submit">@lang('construction::lang.save')</button></div></form></div></div></div>@endcan @endif
    @if(in_array($quote->status, ['draft','sent'], true) && !$quote->project_id)@can('construction.boq.manage')@foreach($quote->items as $item)<div class="modal fade ct-quote-modal" id="ct-quote-item-{{ $item->id }}" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('construction.quotes.items.update',[$quote->id,$item->id]) }}">@csrf @method('PUT')<div class="modal-header"><button class="close" type="button" data-dismiss="modal">&times;</button><h4 class="modal-title">@lang('construction::lang.edit_quote_item')</h4></div><div class="modal-body"><div class="form-group"><label>@lang('construction::lang.boq_code')</label><input name="code" class="form-control" value="{{ $item->code }}" required></div><div class="form-group"><label>@lang('construction::lang.boq_description')</label><input name="description" class="form-control" value="{{ $item->description }}" required></div><div class="row"><div class="col-md-4 form-group"><label>@lang('construction::lang.unit')</label><select name="unit_id" class="form-control" required>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($unit->id===$item->unit_id)>{{ $unit->actual_name }} ({{ $unit->short_name }})</option>@endforeach</select></div><div class="col-md-4 form-group"><label>@lang('construction::lang.quantity')</label><input name="quantity" class="form-control input_number input_quantity" value="{{ @format_quantity((float)$item->quantity) }}" required></div><div class="col-md-4 form-group"><label>@lang('construction::lang.unit_price')</label><input name="unit_price" class="form-control input_number" value="{{ @num_format((float)$item->unit_price) }}" required></div></div><div class="form-group"><label>@lang('construction::lang.notes')</label><textarea name="notes" class="form-control">{{ $item->notes }}</textarea></div></div><div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">@lang('messages.cancel')</button><button class="btn btn-primary">@lang('construction::lang.save')</button></div></form></div></div></div>@endforeach @endcan @endif
@if(!$quote->project_id)@can('construction.boq.approve')<div class="modal fade ct-quote-modal" id="ct-quote-status" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('construction.quotes.status', $quote->id) }}">@csrf<div class="modal-header"><button class="close" type="button" data-dismiss="modal">&times;</button><h4 class="modal-title">@lang('construction::lang.change_quote_status')</h4></div><div class="modal-body"><div class="form-group"><label>@lang('construction::lang.quote_status')</label><select name="status" class="form-control">@foreach(\Modules\Construction\Entities\ConstructionQuote::STATUSES as $state)<option value="{{ $state }}" @selected($state === $quote->status)>@lang('construction::lang.quote_status_'.$state)</option>@endforeach</select></div></div><div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">@lang('messages.cancel')</button><button class="btn btn-primary" type="submit">@lang('construction::lang.save')</button></div></form></div></div></div>@endcan @endif
@if($quote->status === 'accepted' && !$quote->project_id)@can('construction.project.create')<div class="modal fade ct-quote-modal" id="ct-quote-convert" tabindex="-1" role="dialog"><div class="modal-dialog modal-lg" role="document"><div class="modal-content"><form method="POST" action="{{ route('construction.quotes.convert', $quote->id) }}">@csrf<div class="modal-header"><button class="close" type="button" data-dismiss="modal">&times;</button><h4 class="modal-title">@lang('construction::lang.convert_to_project')</h4></div><div class="modal-body">@include('construction::quotes.partials.conversion_fields', ['projectName' => $quote->title])</div><div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">@lang('messages.cancel')</button><button class="btn btn-success" type="submit">@lang('construction::lang.convert_to_project')</button></div></form></div></div></div>@endcan @endif
@endsection

@section('module_javascript')
<script>
$(function(){var body=document.getElementById('ct-quote-entry-rows'), template=document.getElementById('ct-quote-row-template'), add=document.getElementById('ct-quote-add-row'), next=0;if(!body||!template||!add)return;function addRow(){body.insertAdjacentHTML('beforeend',template.innerHTML.replace(/__INDEX__/g,String(next++)));update()}function update(){body.querySelectorAll('tr').forEach(function(row){var qty=parseFloat(row.querySelector('.ct-quote-qty').value)||0,price=parseFloat(row.querySelector('.ct-quote-price').value)||0;row.querySelector('output').textContent=__currency_trans_from_en(qty*price,false)})}add.addEventListener('click',addRow);body.addEventListener('input',update);body.addEventListener('click',function(event){var button=event.target.closest('.ct-quote-remove-row');if(button&&body.rows.length>1){button.closest('tr').remove();update()}});addRow()})
</script>
@endsection
