<style>
.ct-quote-page{padding:12px 0 32px;color:#18345b}.ct-quote-heading,.ct-quote-card{background:#fff;border:1px solid #dfe8f3;border-radius:18px;box-shadow:0 8px 28px rgba(29,66,119,.06)}
.ct-quote-heading{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:24px;margin-bottom:18px}.ct-quote-heading h2{margin:5px 0;font-size:27px;font-weight:800;color:#173b70}.ct-quote-heading p{margin:0;color:#71829b}.ct-quote-eyebrow{font-size:14px;font-weight:700;color:#1769d2}.ct-quote-heading__actions,.ct-quote-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}
.ct-quote-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid #d7e4f3;border-radius:10px;padding:9px 15px;background:#fff;color:#17477f;font-weight:700;cursor:pointer;text-decoration:none}.ct-quote-btn:hover{background:#f0f6ff;text-decoration:none}.ct-quote-btn--primary{background:#1769d2;border-color:#1769d2;color:#fff}.ct-quote-btn--primary:hover{background:#0d56b1;color:#fff}.ct-quote-btn--success{background:#0a8b67;border-color:#0a8b67;color:#fff}.ct-quote-btn--success:hover{background:#087052;color:#fff}
.ct-quote-card{padding:20px;margin-bottom:18px}.ct-quote-card h3{margin:0 0 14px;font-size:18px;font-weight:800;color:#173b70}.ct-quote-list-head{display:flex;gap:12px;justify-content:space-between;align-items:center;margin-bottom:16px}.ct-quote-search{display:flex;gap:8px;max-width:430px;width:100%}.ct-quote-search input{flex:1}
.ct-quote-table-wrap{overflow-x:auto}.ct-quote-table{width:100%;border-collapse:collapse;min-width:760px}.ct-quote-table th{background:#f3f7fc;color:#315377;font-size:14px;font-weight:700}.ct-quote-table th,.ct-quote-table td{padding:12px 10px;border-bottom:1px solid #e8eef7;text-align:right;vertical-align:middle}.ct-quote-table tr:hover td{background:#fbfdff}.ct-quote-table a{font-weight:700}.ct-quote-table tfoot td{background:#eef7ff;font-weight:800;color:#123d91}.ct-quote-num{direction:ltr;text-align:left!important;white-space:nowrap;font-variant-numeric:tabular-nums}.ct-quote-badge{display:inline-block;border-radius:100px;padding:5px 10px;background:#eaf2ff;color:#1769d2;font-size:14px;font-weight:700}.ct-quote-badge--accepted{background:#e8f8ef;color:#087453}.ct-quote-badge--rejected,.ct-quote-badge--expired{background:#fff0ef;color:#ac3a31}.ct-quote-badge--sent{background:#fff7e6;color:#9b6300}.ct-quote-empty{text-align:center;padding:45px 15px;color:#71829b}.ct-quote-empty i{display:block;font-size:32px;margin-bottom:12px;color:#8aa9d0}
.ct-quote-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:18px}.ct-quote-fact{background:#f6f9fd;border:1px solid #e4ecf6;border-radius:12px;padding:12px}.ct-quote-fact small{display:block;color:#73839b;margin-bottom:5px}.ct-quote-fact strong{display:block;color:#24466e;font-size:14px}.ct-quote-total{background:#e8f8ef;border:1px solid #c7ead9;border-radius:12px;padding:14px 18px;color:#087453;text-align:left}.ct-quote-total small{display:block}.ct-quote-total strong{font-size:23px;font-weight:800;direction:ltr}.ct-quote-notice{padding:12px 16px;border-radius:12px;background:#eef7ff;color:#18568b;margin-bottom:18px}.ct-quote-notice--success{background:#e8f8ef;color:#087453}
.ct-quote-entry{width:100%;min-width:780px;border-collapse:collapse}.ct-quote-entry th,.ct-quote-entry td{padding:7px;border-bottom:1px solid #e8eef7}.ct-quote-entry th{background:#f3f7fc}.ct-quote-entry input,.ct-quote-entry select{width:100%;min-width:70px}.ct-quote-entry .ct-quote-wide{min-width:210px}.ct-quote-entry output{white-space:nowrap;color:#0d6b55;font-weight:700}.ct-quote-form-footer{display:flex;justify-content:space-between;gap:12px;margin-top:16px}.ct-quote-modal .modal-content{border-radius:16px;overflow:hidden}.ct-quote-modal .modal-header{background:#f3f7fc}.ct-quote-modal .modal-title{font-weight:800;color:#173b70}.ct-quote-modal .form-group label{font-weight:700}
.ct-quote-actions-heading,.ct-quote-actions-cell{width:112px;min-width:112px;white-space:nowrap}.ct-quote-row-actions{display:flex;align-items:center;gap:5px}.ct-quote-view,.ct-quote-menu-toggle{height:31px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #d7e4f3;border-radius:8px;background:#fff;color:#17477f;font-weight:700}.ct-quote-view{padding:0 9px}.ct-quote-view:hover,.ct-quote-menu-toggle:hover{background:#eef5ff;color:#0d56b1;text-decoration:none}.ct-quote-menu-toggle{width:31px;font-size:22px;line-height:1;cursor:pointer}.ct-quote-menu-toggle:focus-visible,.ct-quote-view:focus-visible{outline:2px solid #1769d2;outline-offset:2px}.ct-quote-menu{display:none;position:fixed;z-index:1060;min-width:182px;padding:5px;background:#fff;border:1px solid #dce6f2;border-radius:10px;box-shadow:0 12px 32px rgba(20,51,87,.18);white-space:normal}.ct-quote-menu a,.ct-quote-menu button{width:100%;display:flex;align-items:center;gap:9px;padding:9px 10px;border:0;border-radius:7px;background:none;color:#24466e;text-align:right;font-size:14px;font-weight:600;cursor:pointer;text-decoration:none}.ct-quote-menu a:hover,.ct-quote-menu button:hover{background:#eef5ff;color:#155bb0}.ct-quote-menu i{width:17px;text-align:center}.ct-quote-menu .ct-quote-menu-danger{border-top:1px solid #edf1f6;border-radius:0;color:#b42318}.ct-quote-menu .ct-quote-menu-danger:hover{background:#fff1ef;color:#9b1c14}.ct-quote-delete-warning{margin:0;padding:13px 15px;border-radius:10px;background:#fff1ef;color:#9b1c14;line-height:1.7}
@media(max-width:800px){.ct-quote-heading{display:block;padding:18px}.ct-quote-heading__actions{margin-top:16px}.ct-quote-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.ct-quote-list-head{display:block}.ct-quote-search{margin-top:12px}.ct-quote-card{padding:14px}}@media(max-width:480px){.ct-quote-facts{grid-template-columns:1fr}.ct-quote-btn{width:100%}.ct-quote-heading__actions,.ct-quote-actions{display:grid;grid-template-columns:1fr 1fr}.ct-quote-actions .ct-quote-btn{width:auto}}
.ct-quote-badge--converted{background:#e8f8ef;color:#087453}
</style>
