@extends('construction::layouts.module')
@section('title', __('construction::lang.new_material_issue'))
@section('module_content')
<section class="content ct-materials-page"><div class="ct-form-shell">
    <div class="ct-form-shell__aside"><a href="{{ route('construction.materials.index') }}" class="ct-back-link"><i class="fa fa-arrow-right"></i> @lang('construction::lang.back_to_materials')</a><span class="ct-form-icon"><i class="fas fa-dolly-flatbed"></i></span><h1>@lang('construction::lang.new_material_issue')</h1><p>@lang('construction::lang.material_issue_draft_hint')</p><div class="ct-form-steps"><div class="is-active"><b>1</b><span><strong>@lang('construction::lang.document_data')</strong><small>@lang('construction::lang.document_data_hint')</small></span></div><div><b>2</b><span><strong>@lang('construction::lang.add_materials_step')</strong><small>@lang('construction::lang.add_materials_step_hint')</small></span></div><div><b>3</b><span><strong>@lang('construction::lang.approve_and_post')</strong><small>@lang('construction::lang.approve_and_post_hint')</small></span></div></div></div>
    <div class="ct-form-shell__main"><div class="ct-form-heading"><span>@lang('construction::lang.step_number', ['number' => 1])</span><h2>@lang('construction::lang.document_identity')</h2><p>@lang('construction::lang.required_fields_hint')</p></div><form method="POST" action="{{ route('construction.materials.store') }}">@csrf<div class="ct-form-grid">
        <div class="form-group"><label>@lang('construction::lang.project') <em>*</em></label><select name="project_id" class="form-control select2" required><option value="">@lang('construction::lang.select_project')</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int)old('project_id') === $project->id)>{{ $project->code }} — {{ $project->name }}</option>@endforeach</select></div>
        <div class="form-group"><label>@lang('construction::lang.source_warehouse') <em>*</em></label><select name="location_id" class="form-control select2" required><option value="">@lang('construction::lang.select_warehouse')</option>@foreach($locations as $id => $name)<option value="{{ $id }}" @selected((int)old('location_id') === (int)$id)>{{ $name }}</option>@endforeach</select></div>
        <div class="form-group"><label>@lang('construction::lang.document_number') <em>*</em></label><div class="ct-input-icon"><i class="fa fa-hashtag"></i><input name="number" value="{{ old('number', $nextNumber) }}" class="form-control" required maxlength="60"></div></div><div class="form-group"><label>@lang('construction::lang.document_date') <em>*</em></label><div class="ct-input-icon"><i class="fa fa-calendar"></i><input name="document_date" value="{{ old('document_date', @format_date(now())) }}" class="form-control ct-date-picker" readonly required></div></div>
        <div class="form-group ct-form-grid__full"><label>@lang('construction::lang.notes')</label><textarea name="notes" class="form-control" rows="4" placeholder="@lang('construction::lang.document_notes_placeholder')">{{ old('notes') }}</textarea></div>
    </div><div class="ct-form-footer"><a href="{{ route('construction.materials.index') }}" class="btn btn-default">@lang('messages.cancel')</a><button class="btn ct-primary-action"><i class="fa fa-arrow-left"></i> @lang('construction::lang.create_draft_and_add_materials')</button></div></form></div>
</div></section>
@endsection
