@extends('construction::layouts.module')
@section('title', __('construction::lang.material_documents'))
@section('module_content')
<section class="content ct-materials-page">
    <div class="ct-materials-hero">
        <div><span class="ct-eyebrow"><i class="fas fa-boxes"></i> @lang('construction::lang.materials_workspace')</span><h1>@lang('construction::lang.material_documents')</h1><p>@lang('construction::lang.material_documents_hint')</p></div>
        @can('construction.material.manage')<a href="{{ route('construction.materials.create') }}" class="btn ct-primary-action"><i class="fa fa-plus"></i> @lang('construction::lang.new_material_issue')</a>@endcan
    </div>
    <div class="ct-material-stat-grid">
        <a href="{{ route('construction.materials.index') }}" class="ct-material-stat {{ !$status && !$type ? 'is-active' : '' }}"><span class="ct-material-stat__icon is-blue"><i class="fas fa-file-alt"></i></span><span><small>@lang('construction::lang.all_documents')</small><strong>{{ $stats['all'] }}</strong></span></a>
        <a href="{{ route('construction.materials.index', ['status' => 'draft']) }}" class="ct-material-stat {{ $status === 'draft' ? 'is-active' : '' }}"><span class="ct-material-stat__icon is-amber"><i class="fas fa-pencil-alt"></i></span><span><small>@lang('construction::lang.draft_documents')</small><strong>{{ $stats['draft'] }}</strong></span></a>
        <a href="{{ route('construction.materials.index', ['status' => 'approved']) }}" class="ct-material-stat {{ $status === 'approved' ? 'is-active' : '' }}"><span class="ct-material-stat__icon is-green"><i class="fas fa-check-circle"></i></span><span><small>@lang('construction::lang.approved_documents')</small><strong>{{ $stats['approved'] }}</strong></span></a>
        <a href="{{ route('construction.materials.index', ['type' => 'issue']) }}" class="ct-material-stat {{ $type === 'issue' ? 'is-active' : '' }}"><span class="ct-material-stat__icon is-violet"><i class="fas fa-truck-loading"></i></span><span><small>@lang('construction::lang.issue_documents')</small><strong>{{ $stats['issues'] }}</strong></span></a>
        <a href="{{ route('construction.materials.index', ['type' => 'return']) }}" class="ct-material-stat {{ $type === 'return' ? 'is-active' : '' }}"><span class="ct-material-stat__icon is-cyan"><i class="fas fa-undo-alt"></i></span><span><small>@lang('construction::lang.return_documents')</small><strong>{{ $stats['returns'] }}</strong></span></a>
    </div>
    <div class="ct-material-panel">
        <form method="GET" class="ct-material-filter">
            <div class="ct-material-filter__search"><label>@lang('construction::lang.search')</label><div class="ct-input-icon"><i class="fa fa-search"></i><input name="q" value="{{ $search }}" class="form-control" placeholder="@lang('construction::lang.search_material_documents')"></div></div>
            <div><label>@lang('construction::lang.project')</label><select name="project_id" class="form-control select2"><option value="">@lang('construction::lang.all_projects')</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected($selectedProjectId === $project->id)>{{ $project->code }} — {{ $project->name }}</option>@endforeach</select></div>
            <div><label>@lang('construction::lang.document_type')</label><select name="type" class="form-control"><option value="">@lang('construction::lang.all_document_types')</option><option value="issue" @selected($type === 'issue')>@lang('construction::lang.material_issue')</option><option value="return" @selected($type === 'return')>@lang('construction::lang.material_return')</option></select></div>
            <div><label>@lang('construction::lang.status')</label><select name="status" class="form-control"><option value="">@lang('construction::lang.all_statuses')</option><option value="draft" @selected($status === 'draft')>@lang('construction::lang.draft')</option><option value="approved" @selected($status === 'approved')>@lang('construction::lang.approved')</option></select></div>
            <div class="ct-material-filter__actions"><button class="btn btn-primary"><i class="fa fa-filter"></i> @lang('construction::lang.apply_filter')</button><a class="btn btn-default" href="{{ route('construction.materials.index') }}" title="@lang('construction::lang.clear_filter')"><i class="fa fa-times"></i></a></div>
        </form>
        <div class="table-responsive"><table class="table ct-material-table"><thead><tr><th>@lang('construction::lang.document_number')</th><th>@lang('construction::lang.document_type')</th><th>@lang('construction::lang.project')</th><th>@lang('construction::lang.date')</th><th>@lang('construction::lang.status')</th><th>@lang('construction::lang.lines_count')</th><th>@lang('construction::lang.amount')</th><th class="text-center">@lang('construction::lang.operations')</th></tr></thead><tbody>
            @forelse($documents as $document)<tr>
                <td><a class="ct-document-link" href="{{ route('construction.materials.show', $document->id) }}"><span class="ct-document-type-icon {{ $document->type === 'return' ? 'is-return' : '' }}"><i class="fas {{ $document->type === 'return' ? 'fa-undo-alt' : 'fa-dolly-flatbed' }}"></i></span><span><strong>{{ $document->number }}</strong><small>{{ $document->location->name }}</small></span></a></td>
                <td><span class="ct-type-pill {{ $document->type === 'return' ? 'is-return' : '' }}">@lang('construction::lang.material_'.$document->type)</span></td>
                <td><strong class="ct-project-name">{{ $document->project->name }}</strong><small class="ct-table-muted">{{ $document->project->code }}</small></td><td>{{ @format_date($document->document_date) }}</td>
                <td><span class="ct-status-pill {{ $document->status === 'approved' ? 'is-approved' : 'is-draft' }}"><i class="fa {{ $document->status === 'approved' ? 'fa-check' : 'fa-clock-o' }}"></i> @lang('construction::lang.'.$document->status)</span></td><td>{{ $document->lines_count }}</td><td><strong class="ct-amount {{ $document->type === 'return' ? 'is-return' : '' }}">@if($document->type === 'return')− @endif @include('construction::partials.money', ['value' => $document->lines_sum_total_cost ?: 0])</strong></td>
                <td class="text-center"><div class="btn-group ct-actions-menu"><button type="button" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ellipsis-h"></i><span>@lang('construction::lang.operations')</span></button><ul class="dropdown-menu dropdown-menu-left"><li><a href="{{ route('construction.materials.show', $document->id) }}"><i class="fa fa-eye"></i> @lang('construction::lang.open_document')</a></li><li><a href="{{ route('construction.materials.preview', $document->id) }}" target="_blank"><i class="fa fa-print"></i> @lang('construction::lang.print_preview')</a></li>@if($document->status === 'draft')@can('construction.material.manage')<li><a href="{{ route('construction.materials.edit', $document->id) }}"><i class="fa fa-pencil"></i> @lang('construction::lang.edit_document')</a></li><li class="divider"></li><li><form method="POST" action="{{ route('construction.materials.destroy', $document->id) }}" onsubmit="return confirm('@lang('construction::lang.delete_material_confirmation')')">@csrf @method('DELETE')<button type="submit" class="ct-dropdown-danger"><i class="fa fa-trash"></i> @lang('construction::lang.delete_draft')</button></form></li>@endcan @elseif($document->type === 'issue')@can('construction.material.manage')<li><a href="{{ route('construction.materials.returns.create', $document->id) }}"><i class="fa fa-undo"></i> @lang('construction::lang.create_material_return')</a></li>@endcan @endif</ul></div></td>
            </tr>@empty<tr><td colspan="8"><div class="ct-empty-state"><span><i class="fas fa-box-open"></i></span><strong>@lang('construction::lang.no_material_documents')</strong><p>@lang('construction::lang.no_material_documents_hint')</p>@can('construction.material.manage')<a href="{{ route('construction.materials.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> @lang('construction::lang.new_material_issue')</a>@endcan</div></td></tr>@endforelse
        </tbody></table></div><div class="ct-panel-pagination">{{ $documents->links() }}</div>
    </div>
</section>
@endsection
