@extends('construction::layouts.module')
@section('title', __('construction::lang.create_material_return'))
@section('module_content')
<section class="content ct-materials-page">
    <div class="ct-return-hero"><div><a href="{{ route('construction.materials.show', $issue->id) }}" class="ct-back-link"><i class="fa fa-arrow-right"></i> {{ $issue->number }}</a><span class="ct-form-icon is-cyan"><i class="fas fa-undo-alt"></i></span><h1>@lang('construction::lang.create_material_return')</h1><p>@lang('construction::lang.material_return_hint', ['number' => $issue->number])</p></div><div class="ct-return-source"><span>@lang('construction::lang.source_issue')</span><strong>{{ $issue->number }}</strong><small>{{ $issue->project->code }} — {{ $issue->project->name }}</small><small><i class="fa fa-warehouse"></i> {{ $issue->location->name }}</small></div></div>
    <form method="POST" action="{{ route('construction.materials.returns.store', $issue->id) }}">@csrf
        <div class="ct-material-panel"><div class="ct-panel-heading"><div><span>@lang('construction::lang.return_document_data')</span><h2>@lang('construction::lang.document_identity')</h2><p>@lang('construction::lang.return_document_data_hint')</p></div></div><div class="ct-return-form"><div class="form-group"><label>@lang('construction::lang.document_number') *</label><div class="ct-input-icon"><i class="fa fa-hashtag"></i><input name="number" value="{{ old('number', $nextNumber) }}" class="form-control" required></div></div><div class="form-group"><label>@lang('construction::lang.document_date') *</label><div class="ct-input-icon"><i class="fa fa-calendar"></i><input name="document_date" value="{{ old('document_date', @format_date(now())) }}" class="form-control ct-date-picker" readonly required></div></div><div class="form-group ct-return-notes"><label>@lang('construction::lang.notes')</label><input name="notes" value="{{ old('notes') }}" class="form-control" placeholder="@lang('construction::lang.document_notes_placeholder')"></div></div></div>
        <div class="ct-material-panel ct-return-lines"><div class="ct-panel-heading"><div><span>@lang('construction::lang.return_quantities')</span><h2>@lang('construction::lang.select_return_quantities')</h2><p>@lang('construction::lang.select_return_quantities_hint')</p></div></div><div class="table-responsive"><table class="table ct-material-table"><thead><tr><th>@lang('construction::lang.material_product')</th><th>@lang('construction::lang.project_item')</th><th>@lang('construction::lang.issued_quantity')</th><th>@lang('construction::lang.previously_returned')</th><th>@lang('construction::lang.available_to_return')</th><th>@lang('construction::lang.return_quantity')</th></tr></thead><tbody>@foreach($issue->lines as $index => $line)@php($remaining = max(0, (float)$line->quantity - (float)($returned[$line->id] ?? 0)))<tr><td><strong>{{ $line->variation->full_name }}</strong><small class="ct-table-muted">{{ $line->product->unit?->short_name }}</small><input type="hidden" name="lines[{{ $index }}][id]" value="{{ $line->id }}"></td><td>{{ $line->boqItem ? $line->boqItem->code.' — '.$line->boqItem->description : __('construction::lang.general_project_material') }}</td><td>{{ @num_format($line->quantity) }}</td><td>{{ @num_format($returned[$line->id] ?? 0) }}</td><td><span class="ct-available-pill {{ $remaining <= 0 ? 'is-empty' : '' }}">{{ @num_format($remaining) }}</span></td><td><input name="lines[{{ $index }}][quantity]" value="{{ old('lines.'.$index.'.quantity', 0) }}" class="form-control input_number ct-quantity-input" @disabled($remaining <= 0)></td></tr>@endforeach</tbody></table></div><div class="ct-form-footer"><a href="{{ route('construction.materials.show', $issue->id) }}" class="btn btn-default">@lang('messages.cancel')</a><button class="btn ct-primary-action"><i class="fa fa-save"></i> @lang('construction::lang.save_return_draft')</button></div></div>
    </form>
</section>
@endsection
