@extends('construction::layouts.module')
@section('title', $document->number)
@section('module_content')
<section class="content ct-materials-page">
    <div class="ct-document-hero">
        <div class="ct-document-hero__identity"><a href="{{ route('construction.materials.index') }}" class="ct-back-link"><i class="fa fa-arrow-right"></i> @lang('construction::lang.back_to_materials')</a><div class="ct-document-title"><span class="ct-document-title__icon {{ $document->type === 'return' ? 'is-return' : '' }}"><i class="fas {{ $document->type === 'return' ? 'fa-undo-alt' : 'fa-dolly-flatbed' }}"></i></span><div><div class="ct-document-kicker">@lang('construction::lang.material_'.$document->type) <span class="ct-status-pill {{ $document->status === 'approved' ? 'is-approved' : 'is-draft' }}">@lang('construction::lang.'.$document->status)</span></div><h1>{{ $document->number }}</h1><p>{{ $document->project->code }} — {{ $document->project->name }}</p></div></div></div>
        <div class="ct-document-actions"><a href="{{ route('construction.materials.preview', $document->id) }}" target="_blank" class="btn btn-default"><i class="fa fa-eye"></i> @lang('construction::lang.print_preview')</a><a href="{{ route('construction.materials.print', $document->id) }}" target="_blank" class="btn btn-primary"><i class="fa fa-print"></i> @lang('construction::lang.print')</a>@if($document->isEditable())@can('construction.material.manage')<a href="{{ route('construction.materials.edit', $document->id) }}" class="btn btn-default"><i class="fa fa-pencil"></i> @lang('construction::lang.edit_document')</a>@endcan @elseif($document->type === 'issue')@can('construction.material.manage')<a href="{{ route('construction.materials.returns.create', $document->id) }}" class="btn btn-default"><i class="fa fa-undo"></i> @lang('construction::lang.create_material_return')</a>@endcan @endif</div>
    </div>
    <div class="ct-document-summary">
        <div><span><i class="fa fa-calendar"></i></span><small>@lang('construction::lang.document_date')</small><strong>{{ @format_date($document->document_date) }}</strong></div><div><span><i class="fa fa-warehouse"></i></span><small>@lang('construction::lang.source_warehouse')</small><strong>{{ $document->location->name }}</strong></div><div><span><i class="fa fa-list"></i></span><small>@lang('construction::lang.lines_count')</small><strong>{{ $document->lines->count() }}</strong></div><div><span><i class="fa fa-coins"></i></span><small>@lang('construction::lang.document_total')</small><strong>@include('construction::partials.money', ['value' => $document->lines->sum('total_cost')])</strong></div>
    </div>
    @if($document->parentIssue)<div class="ct-context-banner"><i class="fa fa-link"></i><span>@lang('construction::lang.return_for_issue') <a href="{{ route('construction.materials.show', $document->parentIssue->id) }}">{{ $document->parentIssue->number }}</a></span></div>@endif
    @if($document->notes)<div class="ct-context-banner is-note"><i class="fa fa-sticky-note"></i><span><strong>@lang('construction::lang.notes'):</strong> {{ $document->notes }}</span></div>@endif

    @if($document->isEditable() && $document->type === 'issue')@can('construction.material.manage')
    <div class="ct-material-panel ct-material-entry"><div class="ct-panel-heading"><div><span>@lang('construction::lang.draft')</span><h2>@lang('construction::lang.add_material')</h2><p>@lang('construction::lang.stock_changes_after_approval')</p></div><div class="ct-step-badge"><b>2</b> @lang('construction::lang.step_number', ['number' => 2])</div></div><form method="POST" action="{{ route('construction.materials.lines.store', $document->id) }}">@csrf<div class="ct-entry-grid"><div class="form-group ct-entry-product"><label>@lang('construction::lang.material_product') *</label><select name="variation_id" class="form-control select2" required><option value="">@lang('construction::lang.select_material')</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->product_name }}@if($product->group_name !== 'DUMMY') — {{ $product->group_name }} / {{ $product->variation_name }}@endif ({{ $product->sub_sku }}) — @lang('construction::lang.available'): {{ @num_format($product->qty_available) }}</option>@endforeach</select></div><div class="form-group"><label>@lang('construction::lang.quantity') *</label><input name="quantity" class="form-control input_number" required></div><div class="form-group"><label>@lang('construction::lang.project_item_optional')</label><select name="boq_item_id" class="form-control select2"><option value="">@lang('construction::lang.general_project_material')</option>@foreach($boqItems as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ $item->description }}</option>@endforeach</select></div><div class="form-group ct-entry-notes"><label>@lang('construction::lang.notes')</label><input name="notes" class="form-control" placeholder="@lang('construction::lang.line_notes_optional')"></div><button class="btn ct-primary-action"><i class="fa fa-plus"></i> @lang('construction::lang.add_material')</button></div></form></div>
    @endcan @endif

    <div class="ct-material-panel"><div class="ct-panel-heading"><div><span>@lang('construction::lang.document_details')</span><h2>@lang('construction::lang.material_lines')</h2><p>@lang('construction::lang.material_lines_hint')</p></div></div><div class="table-responsive"><table class="table ct-material-table"><thead><tr><th>#</th><th>@lang('construction::lang.material_product')</th><th>@lang('construction::lang.project_item')</th><th>@lang('construction::lang.quantity')</th>@if($document->type === 'issue')<th>@lang('construction::lang.returned_quantity')</th>@endif<th>@lang('construction::lang.unit_cost')</th><th>@lang('construction::lang.total_cost')</th>@if($document->isEditable())<th class="text-center">@lang('construction::lang.operations')</th>@endif</tr></thead><tbody>
        @forelse($document->lines as $line)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $line->variation->full_name }}</strong><small class="ct-table-muted">{{ $line->product->unit?->short_name }}@if($line->notes) · {{ $line->notes }}@endif</small></td><td>{{ $line->boqItem ? $line->boqItem->code.' — '.$line->boqItem->description : __('construction::lang.general_project_material') }}</td><td><strong>{{ @num_format($line->quantity) }}</strong></td>@if($document->type === 'issue')<td>{{ @num_format($returnedBySource[$line->id] ?? 0) }}</td>@endif<td>@include('construction::partials.money', ['value' => $line->unit_cost])</td><td><strong>@include('construction::partials.money', ['value' => $line->total_cost])</strong></td>
            @if($document->isEditable())<td class="text-center">@can('construction.material.manage')<button class="btn btn-xs btn-default" data-toggle="modal" data-target="#edit-line-{{ $line->id }}" title="@lang('construction::lang.edit_line')"><i class="fa fa-pencil"></i></button><form class="ct-inline-form" method="POST" action="{{ route('construction.materials.lines.destroy', [$document->id, $line->id]) }}" onsubmit="return confirm('@lang('messages.sure')')">@csrf @method('DELETE')<button class="btn btn-xs btn-danger" title="@lang('construction::lang.delete_line')"><i class="fa fa-trash"></i></button></form>@endcan</td>@endif
        </tr>@empty<tr><td colspan="8"><div class="ct-empty-state is-compact"><span><i class="fas fa-box-open"></i></span><strong>@lang('construction::lang.material_document_empty')</strong></div></td></tr>@endforelse
    </tbody>@if($document->lines->isNotEmpty())<tfoot><tr><th colspan="{{ $document->type === 'issue' ? 6 : 5 }}" class="text-left">@lang('construction::lang.document_total')</th><th>@include('construction::partials.money', ['value' => $document->lines->sum('total_cost')])</th>@if($document->isEditable())<th></th>@endif</tr></tfoot>@endif</table></div>
        @if($document->isEditable())@can('construction.material.approve')<div class="ct-approval-bar"><div><i class="fa fa-shield"></i><span><strong>@lang('construction::lang.ready_for_approval')</strong><small>@lang('construction::lang.approval_locks_document')</small></span></div><form method="POST" action="{{ route('construction.materials.approve', $document->id) }}" onsubmit="return confirm('@lang('construction::lang.approve_material_confirmation')')">@csrf<button class="btn btn-success" @disabled($document->lines->isEmpty())><i class="fa fa-check-circle"></i> @lang('construction::lang.approve_and_post_stock')</button></form></div>@endcan @endif
    </div>
</section>
@if($document->isEditable())@foreach($document->lines as $line)<div class="modal fade" id="edit-line-{{ $line->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content ct-modern-modal"><form method="POST" action="{{ route('construction.materials.lines.update', [$document->id, $line->id]) }}">@csrf @method('PUT')<div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><span class="ct-form-icon is-small"><i class="fa fa-pencil"></i></span><h4 class="modal-title">@lang('construction::lang.edit_line')</h4><p>{{ $line->variation->full_name }}</p></div><div class="modal-body"><div class="form-group"><label>@lang('construction::lang.quantity') *</label><input name="quantity" value="{{ @num_format($line->quantity) }}" class="form-control input_number" required></div>@if($document->type === 'issue')<div class="form-group"><label>@lang('construction::lang.project_item_optional')</label><select name="boq_item_id" class="form-control"><option value="">@lang('construction::lang.general_project_material')</option>@foreach($boqItems as $item)<option value="{{ $item->id }}" @selected($line->boq_item_id === $item->id)>{{ $item->code }} — {{ $item->description }}</option>@endforeach</select></div>@endif<div class="form-group"><label>@lang('construction::lang.notes')</label><textarea name="notes" class="form-control" rows="3">{{ $line->notes }}</textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">@lang('messages.cancel')</button><button class="btn btn-primary"><i class="fa fa-save"></i> @lang('construction::lang.save_changes')</button></div></form></div></div></div>@endforeach @endif
@endsection
