@extends('construction::layouts.module')
@section('title', __('construction::lang.contract_adjustments'))
@section('module_content')
<section class="content" dir="rtl">
    <div class="box box-solid">
        <div class="box-header with-border"><h3 class="box-title">@lang('construction::lang.contract_adjustments') — {{ $project->name }}</h3><div class="box-tools"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#ct-adjustment-create"><i class="fa fa-plus"></i> @lang('construction::lang.add_contract_adjustment')</button> <a class="btn btn-default btn-sm" href="{{ route('construction.projects.contracts.show', [$project->id, $contract->id]) }}">@lang('construction::lang.back_to_contract')</a></div></div>
        <div class="box-body"><p class="text-muted">@lang('construction::lang.adjustments_history_hint')</p>
            <div class="table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>@lang('construction::lang.status')</th><th>@lang('construction::lang.boq_code')</th><th>@lang('construction::lang.boq_description')</th><th>@lang('construction::lang.unit')</th><th>@lang('construction::lang.quantity')</th><th>@lang('construction::lang.unit_price')</th><th>@lang('construction::lang.total')</th><th>@lang('construction::lang.adjustment_reason')</th><th>@lang('construction::lang.date')</th><th>@lang('construction::lang.actions')</th></tr></thead><tbody>
            @forelse($adjustments as $adjustment)<tr><td><span class="ct-status ct-status--{{ $adjustment->status }}">@lang('construction::lang.'.$adjustment->status)</span></td><td>{{ $adjustment->boqItem?->code ?: ($adjustment->code ?: '—') }}</td><td><strong>{{ $adjustment->description }}</strong>@if($adjustment->originalItem)<small class="help-block">@lang('construction::lang.linked_original_item'): {{ $adjustment->originalItem->code }} — @lang('construction::lang.original_quantity'): {{ @format_quantity((float)$adjustment->originalItem->contract_quantity) }} / @lang('construction::lang.current_authorized_quantity'): {{ @format_quantity((float)$adjustment->originalItem->contract_quantity + (float)$contract->adjustments()->where('status','approved')->where('original_boq_item_id',$adjustment->original_boq_item_id)->sum('quantity')) }}</small>@endif</td><td>{{ $adjustment->unit }}</td><td>{{ @format_quantity((float)$adjustment->quantity) }}</td><td>@include('construction::partials.money',['value'=>$adjustment->unit_price])</td><td>@include('construction::partials.money',['value'=>$adjustment->total])</td><td>{{ $adjustment->reason }}</td><td>{{ @format_date($adjustment->adjustment_date) }}</td><td>@if($adjustment->status === 'draft')@can('construction.contract.approve')<form method="POST" action="{{ route('construction.projects.contracts.adjustments.approve',[$project->id,$contract->id,$adjustment->id]) }}" style="display:inline" onsubmit="return confirm('{{ __('construction::lang.approve_adjustment_confirmation') }}')">@csrf<button class="btn btn-xs btn-success"><i class="fa fa-check"></i> @lang('construction::lang.approve')</button></form>@endcan @can('construction.contract.manage')<form method="POST" action="{{ route('construction.projects.contracts.adjustments.destroy',[$project->id,$contract->id,$adjustment->id]) }}" style="display:inline">@csrf @method('DELETE')<button class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button></form>@endcan @else<i class="fa fa-lock text-muted"></i>@endif</td></tr>
            @empty<tr><td colspan="10" class="text-center text-muted">@lang('construction::lang.no_contract_adjustments')</td></tr>@endforelse
            </tbody></table></div>
        </div>
    </div>
</section>
@can('construction.contract.manage')
<div class="modal fade ct-quick-modal" id="ct-adjustment-create" tabindex="-1" role="dialog"><div class="modal-dialog modal-lg" role="document"><div class="modal-content"><form method="POST" action="{{ route('construction.projects.contracts.adjustments.store',[$project->id,$contract->id]) }}">@csrf
<div class="modal-header"><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button><h4 class="modal-title">@lang('construction::lang.add_contract_adjustment')</h4></div><div class="modal-body">
<div class="form-group"><label>@lang('construction::lang.adjustment_type')</label><select name="original_boq_item_id" id="ct-adjustment-source" class="form-control"><option value="">@lang('construction::lang.new_additional_item')</option>@foreach($contract->boqVersion->items as $item)<option value="{{ $item->id }}" data-code="{{ $item->code }}" data-description="{{ $item->description }}" data-unit="{{ $item->unit_id }}" data-price="{{ (float)$item->sales_unit_price }}">@lang('construction::lang.increase_existing_item'): {{ $item->code }} — {{ $item->description }}</option>@endforeach</select></div>
<div class="row"><div class="col-md-3 form-group"><label>@lang('construction::lang.boq_code')</label><input name="code" id="ct-adjustment-code" class="form-control" maxlength="60"></div><div class="col-md-9 form-group"><label>@lang('construction::lang.work_description') *</label><input name="description" id="ct-adjustment-description" class="form-control" maxlength="500" required></div></div>
<div class="row"><div class="col-md-3 form-group"><label>@lang('construction::lang.unit') *</label><select name="unit_id" id="ct-adjustment-unit" class="form-control" required><option value="">@lang('construction::lang.choose')</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->actual_name }} ({{ $unit->short_name }})</option>@endforeach</select></div><div class="col-md-3 form-group"><label>@lang('construction::lang.additional_quantity') *</label><input name="quantity" id="ct-adjustment-quantity" class="form-control input_number input_quantity" required></div><div class="col-md-3 form-group"><label>@lang('construction::lang.unit_price') *</label><input name="unit_price" id="ct-adjustment-price" class="form-control input_number" required></div><div class="col-md-3 form-group"><label>@lang('construction::lang.total')</label><input id="ct-adjustment-total" class="form-control" readonly></div></div>
<div class="row"><div class="col-md-8 form-group"><label>@lang('construction::lang.adjustment_reason') *</label><input name="reason" class="form-control" maxlength="500" required></div><div class="col-md-4 form-group"><label>@lang('construction::lang.date') *</label><input name="adjustment_date" class="form-control ct-date-picker" value="{{ @format_date(now()) }}" readonly required></div></div>
<div class="form-group"><label>@lang('construction::lang.optional_notes')</label><textarea name="notes" class="form-control" rows="3" maxlength="5000"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">@lang('messages.cancel')</button><button class="btn btn-primary"><i class="fa fa-save"></i> @lang('construction::lang.save_as_draft')</button></div></form></div></div></div>
@endcan
@endsection
@section('module_javascript')
<script>$(function(){ $('.ct-date-picker').datetimepicker({format:moment_date_format,ignoreReadonly:true}); function total(){var q=__number_uf($('#ct-adjustment-quantity').val())||0,p=__number_uf($('#ct-adjustment-price').val())||0;$('#ct-adjustment-total').val(__currency_trans_from_en(q*p,false));} $('#ct-adjustment-source').on('change',function(){var o=$(this).find(':selected');if(o.val()){ $('#ct-adjustment-code').val(o.data('code')+'-V');$('#ct-adjustment-description').val(o.data('description'));$('#ct-adjustment-unit').val(String(o.data('unit')));__write_number($('#ct-adjustment-price'),parseFloat(o.data('price'))||0);} total();});$('#ct-adjustment-quantity,#ct-adjustment-price').on('input change',total);total();});</script>
@endsection
