@php
$supplierName = $contract->subcontractor->supplier_business_name ?: $contract->subcontractor->name;
$logoSource = !empty($business->logo) ? public_path('uploads/business_logos/'.$business->logo) : null;
if ($logoSource && !is_file($logoSource)) $logoSource = null;
$companyAddress = collect([$businessLocation?->landmark, $businessLocation?->city, $businessLocation?->state, $businessLocation?->country])->filter()->implode('، ');
@endphp
<!doctype html><html lang="{{ app()->getLocale() }}" dir="rtl"><head><meta charset="utf-8"><title>{{ $payment->number }}</title><style>
*{box-sizing:border-box}body{margin:0;background:#edf2f7;color:#193755;font-family:Arial,sans-serif}.toolbar{display:flex;justify-content:center;gap:8px;padding:15px}.toolbar button{padding:9px 22px;border:0;border-radius:7px;background:#1769d2;color:#fff;font-weight:700}.voucher{position:relative;width:190mm;min-height:125mm;margin:0 auto 24px;padding:12mm 14mm;background:#fff;box-shadow:0 12px 40px rgba(20,48,80,.18);overflow:hidden}.accent{height:6px;margin:-12mm -14mm 8mm;background:#174f8c}.header{display:grid;grid-template-columns:1fr auto;align-items:center;padding-bottom:7mm;border-bottom:1px solid #dfe7ef}.company{display:flex;align-items:center;gap:12px}.company img{max-width:38mm;max-height:17mm}.company strong,.company small{display:block}.company strong{font-size:18px}.company small,.address{color:#75869a;font-size:10px}.address{text-align:left}.title{text-align:center;margin:8mm 0}.title h1{margin:0 0 7px;color:#174f8c;font-size:23px}.number{display:inline-block;padding:5px 14px;border-radius:18px;background:#eaf3ff;font-weight:900;direction:ltr}.amount{margin:0 auto 8mm;padding:14px;border:2px solid #174f8c;border-radius:12px;text-align:center;background:#f4f8fd}.amount small,.amount strong{display:block}.amount small{color:#74869a}.amount strong{margin-top:5px;color:#174f8c;font-size:28px}.details{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.details div{padding:9px 11px;border:1px solid #dfe7ef;border-radius:8px}.details small,.details strong{display:block}.details small{margin-bottom:4px;color:#7a899b;font-size:10px}.details strong{font-size:12px}.notes{margin-top:8px;padding:10px;border:1px solid #dfe7ef;border-radius:8px;font-size:11px}.signatures{display:grid;grid-template-columns:repeat(4,1fr);gap:9mm;margin-top:18mm;text-align:center;font-size:11px;font-weight:800}.signatures div{padding-top:17mm;border-top:1px solid #6f7f90}.stamp{position:absolute;left:15mm;top:35mm;padding:8px 14px;border:2px solid #1b9668;border-radius:7px;color:#1b9668;font-weight:900;transform:rotate(-8deg)}@media print{body{background:#fff}.toolbar{display:none}.voucher{width:auto;margin:0;box-shadow:none}@page{size:A4 portrait;margin:10mm}}
@include('construction::partials.print_typography')</style></head><body>
<div class="toolbar"><button onclick="window.print()">@lang('construction::lang.print_document')</button><button onclick="window.close()">@lang('construction::lang.close_preview')</button></div>
<main class="voucher"><div class="accent"></div><div class="header"><div class="company">@if($logoSource)<img src="{{ $logoSource }}">@endif<div><strong>{{ $business->name }}</strong><small>{{ $businessLocation?->name }}</small></div></div><div class="address">{{ $companyAddress }}</div></div>
<div class="stamp">@lang('construction::lang.recorded')</div>
<div class="title"><h1>@lang('construction::lang.subcontract_payment_receipt')</h1><span class="number">{{ $payment->number }}</span></div>
<div class="amount"><small>@lang('construction::lang.payment_amount')</small><strong>@include('construction::partials.money',['value'=>$payment->amount])</strong></div>
<div class="details"><div><small>@lang('construction::lang.subcontractor')</small><strong>{{ $supplierName }}</strong></div><div><small>@lang('construction::lang.payment_date')</small><strong>{{ @format_date($payment->payment_date) }}</strong></div><div><small>@lang('construction::lang.project')</small><strong>{{ $contract->project->code }} — {{ $contract->project->name }}</strong></div><div><small>@lang('construction::lang.certificate_number')</small><strong dir="ltr">{{ $certificate->number }}</strong></div><div><small>@lang('construction::lang.payment_method')</small><strong>{{ $paymentMethod }}</strong></div><div><small>@lang('construction::lang.payment_account')</small><strong>{{ $payment->accountingAccount?->name ?: ($payment->account?->name ?: '—') }}</strong></div><div><small>@lang('construction::lang.payment_reference')</small><strong>{{ $payment->reference_no ?: '—' }}</strong></div><div><small>@lang('construction::lang.agreement_number')</small><strong dir="ltr">{{ $contract->number }}</strong></div></div>
@if($payment->notes)<div class="notes"><strong>@lang('construction::lang.notes'):</strong> {{ $payment->notes }}</div>@endif
<div class="signatures"><div>@lang('construction::lang.prepared_by')</div><div>@lang('construction::lang.cashier_signature')</div><div>@lang('construction::lang.accounting_signature')</div><div>@lang('construction::lang.received_by')</div></div>
</main>@if($autoPrint)<script>window.addEventListener('load',function(){window.print()})</script>@endif</body></html>
